---
title: "Modeling Comorb"
author: "Team 6"
date: '2022-07-15'
output: html_document
---

```{r}
setwd("C:/Users/lizvi/Cal State Fullerton/Jaynes, Jessica - CSUF CHOC Summer 2022 Research/Group2")

load("cfCOVIDgroup6.RDATA")

library(tidyverse)
library(viridis)
library(glmnet)
library(gee)
```


```{r message = FALSE}
attach(d)

all_comorb <- d %>% 
  select(encounterid, personid, servicedate, contains("comorb"),
         COVIDseverity, age_at_encounter) %>% 
  mutate(servicedate = as.Date(d[,"servicedate"]), 
         COVIDseverity = as.ordered(case_when(COVIDseverity > 0 ~ 1,
                                   COVIDseverity == 0 ~ 0)),
         personid = as.factor(personid),
         age_group = as.factor(case_when(age_at_encounter <= 11 ~ "0 - 11",
                               age_at_encounter > 11 & 
                                 age_at_encounter <= 17 ~ "12 - 17",
                               age_at_encounter > 17 &
                                 age_at_encounter < 21 ~ "18 - 20",
                               age_at_encounter > 20 ~ "21 - 25")),
         payer = as.factor(payer))

first_enc <- all_comorb %>%
  arrange_at("servicedate") %>%
  distinct(personid, .keep_all = TRUE)

table(first_enc$age_at_encounter)/length(first_enc$age_at_encounter)

cumsum(table(first_enc$age_at_encounter)/length(first_enc$age_at_encounter))  

first_enc_all <- d %>% 
   mutate(servicedate = as.Date(d[,"servicedate"]), 
          personid = as.factor(personid)) %>% 
  arrange_at("servicedate") %>% 
  distinct(personid, .keep_all = TRUE)
          
```


Shows total occurrence of each comorbidity in data set
```{r warning = FALSE}
totalco <- first_enc[,4:24] %>% 
  mutate_if(is.factor, as.numeric) %>%
  - 1 %>%
  colSums()

totalco
```


```{r}
table(first_enc$payer)

glm(COVIDseverity ~ payer, data = first_enc, family = "binomial") %>% 
  summary()
```


```{r}
glm(COVIDseverity ~., data = first_enc[,c(4:26, 28)], family = "binomial") %>% 
  summary()
```


Logistic Regression now with grouped ages based on proportion. Each age group is
roughly 25% of the sample. 
```{r}

glm(COVIDseverity ~ ., 
               data = first_enc[,c(4:25, 27:28)], family = "binomial") %>% 
  summary()
```


With ages grouped by WHO standard
```{r}
all_comorb_WHO <- d %>% 
  select(encounterid, personid, servicedate, contains("comorb"),
         COVIDseverity, age_at_encounter) %>% 
  mutate(servicedate = as.Date(d[,"servicedate"]), 
         COVIDseverity = as.ordered(case_when(COVIDseverity > 0 ~ 1,
                                   COVIDseverity == 0 ~ 0)),
         personid = as.factor(personid),
         age_group = as.factor(case_when(age_at_encounter <= 4 ~ "0 - 4",
                               age_at_encounter > 4 & 
                                 age_at_encounter < 10 ~ "5 - 9",
                               age_at_encounter > 9 &
                                 age_at_encounter < 15 ~ "10 - 14",
                               age_at_encounter > 14 &
                                 age_at_encounter < 20 ~ "15 - 19",
                               age_at_encounter > 19 ~ "20 - 25")),
         payer = as.factor(payer))

first_enc_WHO <- all_comorb_WHO %>%
  distinct(personid, .keep_all = TRUE)

glm(COVIDseverity ~ ., 
               data = first_enc_WHO[,c(4:25, 27:28)], family = "binomial") %>% 
  summary()
```


LASSO ?!!!?!!!
```{r}
set.seed(622)
x <-  model.matrix(COVIDseverity ~., first_enc[,c(4:28)])[, -1]
y <-  first_enc$COVIDseverity

grid <- 10^seq(10, -2, length = 100)

train <-  sample(nrow(x), size = floor(.8 * nrow(x)))
test <-  (-train)
y_test <-  y[test]

lasso_mod <-  glmnet(x[train, ], y[train], alpha = 1,
                     lambda = grid, family = "binomial")

cv_out <- cv.glmnet(x[train, ], y[train], alpha = 1, family = "binomial")

best_lam <-  cv_out$lambda.min

lasso_pred <-  predict(lasso_mod, s = best_lam, newx = x[test, ])

out <-  glmnet(x, y, alpha = 1, lambda = grid, family = "binomial")

lasso_coef = predict(out, type = "coefficients",
                         s = best_lam)[1:27, ]

lasso_coef[lasso_coef != 0]
```

```{r}


olr_df <- d %>% 
  select(contains("comorb"),
         COVIDseverity, age_at_encounter) %>% 
  mutate(servicedate = as.Date(d[,"servicedate"]),
         personid = as.factor(personid),
         age_group = as.factor(case_when(age_at_encounter <= 11 ~ "0 - 11",
                               age_at_encounter > 11 & 
                                 age_at_encounter <= 17 ~ "12 - 17",
                               age_at_encounter > 17 &
                                 age_at_encounter < 21 ~ "18 - 20",
                               age_at_encounter > 20 ~ "21 - 25")),
         payer = as.factor(payer)) %>% 
  arrange_at("servicedate") %>%
  distinct(personid, .keep_all = TRUE)

library(MASS)

train <-  sample(nrow(olr_df), size = floor(.80 * nrow(olr_df)))

dtrain <- olr_df[train,]
test <- olr_df[-train,]

olr_fit <- polr(COVIDseverity ~ comorb_bronchiectasis_J47 +
                comorb_resp_failure_J96 + comorb_malnutrition + 
                comorb_other_GI_notLiver_K_excludesK70K77 +
                comorb_chronic_kidney_disease_N18 +
                comorb_nicotine_dependence_F17 + 
                comorb_heart_failure_I50, data = dtrain,
              Hess = TRUE)


glm_probs = predict(olr_fit, test)

table(test$COVIDseverity, glm_probs)
mean(as.character(olr_df[-train,]$COVIDseverity) != as.character(COVIDseverity))

```

```{r}
payer_olr <- polr(COVIDseverity ~ payer, data = dtrain, Hess = TRUE)

payer_probs = predict(payer_olr, test)

table(test$COVIDseverity, payer_probs)
mean(as.character(olr_df[-train,]$COVIDseverity) != as.character(COVIDseverity))


```


