---
title: "Untitled"
author: "Neo Raquinio"
date: '2022-07-07'
output: html_document
---
```{r}
library(tidyverse)

#### USEFUL COMMANDS ####

#typeof() checks variable type

```

```{r}

choc <- d %>% 
  mutate(
        comorb_bronchiectasis_J47 = as.integer(comorb_bronchiectasis_J47)-1,
        comorb_copd_J40_J44 = as.integer(comorb_copd_J40_J44)-1,
        comorb_asthma_J45 = as.integer(comorb_asthma_J45)-1,
        comorb_nasal_polyps_J33 = as.integer(comorb_nasal_polyps_J33)-1,
        comorb_hemoptysisR042 = as.integer(comorb_hemoptysisR042)-1,
        comorb_pneumothorax_J93 = as.integer(comorb_pneumothorax_J93)-1,
        comorb_resp_failure_J96 = as.integer(comorb_resp_failure_J96)-1,
        comorb_malnutrition = as.integer(comorb_malnutrition)-1,
        comorb_other_nutritional_deficiencies_E50_E64 = as.integer(comorb_other_nutritional_deficiencies_E50_E64)-1,
        comorb_typeI_diabetes_E10 = as.integer(comorb_typeI_diabetes_E10)-1,
        comorb_typeII_diabetes_E11 = as.integer(comorb_typeII_diabetes_E11)-1,
        comorb_obesity_overweight_E66 = as.integer(comorb_obesity_overweight_E66)-1,
        comorb_liver_disease_K70_K77 = as.integer(comorb_liver_disease_K70_K77)-1,
        comorb_other_GI_notLiver_K_excludesK70K77 = as.integer(comorb_other_GI_notLiver_K_excludesK70K77)-1,
        comorb_essential_hypertension_I10 = as.integer(comorb_essential_hypertension_I10)-1,
        comorb_hypertensive_heart_disease_I11 = as.integer(comorb_hypertensive_heart_disease_I11)-1,
        comorb_chronic_kidney_disease_N18 = as.integer(comorb_chronic_kidney_disease_N18)-1,
        comorb_nicotine_dependence_F17 = as.integer(comorb_nicotine_dependence_F17)-1,
        comorb_heart_failure_I50 = as.integer(comorb_heart_failure_I50)-1,
        comorb_ischemic_heart_disease_I20_I25 = as.integer(comorb_ischemic_heart_disease_I20_I25)-1,
        comorb_lung_transplant_Z942 = as.integer(comorb_lung_transplant_Z942)-1,
        servicedate = as.Date(d[,9]),
        dischargedate = as.Date(d[,10])
        )

total_comorb = rowSums(choc[,15:35])

choc <- choc %>% 
  mutate(total_comorb = total_comorb)

care_time <- as.numeric(difftime(choc$dischargedate, choc$servicedate, units = "days"))

choc <- choc %>% 
  mutate(care_time = care_time)

glimpse(choc)

max(care_time, na.rm = T)

```

```{r}
ggplot(choc, aes(as.factor(total_comorb), care_time, color = COVIDseverity)) +
  geom_jitter() +
  labs(x = "Total Comorbidity", y = "Time in Care (Days)") +
  ggtitle("Time in Care by Total Comorbidities") +
  scale_color_manual(values = c("#EDD9A3", "#F2637F", "#872CA2"), labels = c("Mild", "Moderate", "Severe"))

```



```{r}

choc <- choc %>% 
  mutate(
    ECMO = as.numeric(as.character(ECMO)),
    HFNC = as.numeric(as.character(HFNC)),
    NC = as.numeric(as.character(NC)),
    bipapCpapNonInvasive = as.numeric(as.character(bipapCpapNonInvasive)),
    invasiveMechVentilation = as.numeric(as.character(invasiveMechVentilation)),
    DELIRIUM = as.numeric(as.character(DELIRIUM)),
    INOTROPES = as.numeric(as.character(INOTROPES)),
    REMDESIVIR = as.numeric(as.character(REMDESIVIR)),
    CCP = as.numeric(as.character(CCP)),
    DEXAMETHASONE = as.numeric(as.character(DEXAMETHASONE)),
    ENOXAPARIN = as.numeric(as.character(ENOXAPARIN)),
    HEPARIN = as.numeric(as.character(HEPARIN)),
    IVIG = as.numeric(as.character(IVIG)),
    METHYLPREDNISOLONE = as.numeric(as.character(METHYLPREDNISOLONE)),
    RITUXIMAB = as.numeric(as.character(RITUXIMAB)),
    TOCILIZUMAB = as.numeric(as.character(TOCILIZUMAB)),
    ASPIRIN = as.numeric(as.character(ASPIRIN)),
    LOPINAVIR_OR_RITONAVIR = as.numeric(as.character(LOPINAVIR_OR_RITONAVIR))
  )

total_treatments = rowSums(choc[,36:53])

choc %>% 
  mutate(
    total_treatments = total_treatments
  )

choc %>% 
  summarise(
    min(total_treatments),
    max(total_treatments),
    median(total_treatments),
    mean(total_treatments)
  )


ggplot(choc, aes(x = as.factor(total_treatments), y = care_time, color = COVIDseverity)) +
  geom_jitter() +
  scale_color_manual(values = c("#EDD9A3", "#F2637F", "#872CA2"), labels = c("Mild", "Moderate", "Severe"))
  
```




