---
title: "EDA1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/Users/rasulibragimov/Cal State Fullerton/Jaynes, Jessica - Group2")
dir()
load("cfCOVIDgroup6.RDATA")

View(d)
library(tidyverse)
library(janitor)
library(corrr)
library(ggplot2)
library(dplyr)
library(scales)

choc <- d



all_comorb <- select(choc, personid, contains("comorb"))

```

```{r}
#converts the comorb variables into numeric variables
choc <- choc %>% 
  mutate(comorb_bronchiectasis_J47 = as.double(comorb_bronchiectasis_J47)-1,
         comorb_copd_J40_J44 = as.double(comorb_copd_J40_J44)-1,
         comorb_asthma_J45 = as.double(comorb_asthma_J45)-1,
         comorb_nasal_polyps_J33 = as.double(comorb_nasal_polyps_J33)-1,
         comorb_hemoptysisR042 = as.double(comorb_hemoptysisR042)-1,
         comorb_pneumothorax_J93 = as.double(comorb_pneumothorax_J93)-1,
         comorb_resp_failure_J96 = as.double(comorb_resp_failure_J96)-1,
         comorb_malnutrition = as.double(comorb_malnutrition)-1,
         comorb_other_nutritional_deficiencies_E50_E64 = as.double(comorb_other_nutritional_deficiencies_E50_E64)-1,
         comorb_typeI_diabetes_E10 = as.double(comorb_typeI_diabetes_E10)-1,
         comorb_typeII_diabetes_E11 = as.double(comorb_typeII_diabetes_E11)-1,
         comorb_obesity_overweight_E66 = as.double(comorb_obesity_overweight_E66)-1,
         comorb_liver_disease_K70_K77 = as.double(comorb_liver_disease_K70_K77)-1,
         comorb_other_GI_notLiver_K_excludesK70K77 = as.double(comorb_other_GI_notLiver_K_excludesK70K77)-1,
         comorb_essential_hypertension_I10 = as.double(comorb_essential_hypertension_I10)-1,
         comorb_hypertensive_heart_disease_I11 = as.double(comorb_hypertensive_heart_disease_I11)-1,
         comorb_chronic_kidney_disease_N18 = as.double(comorb_chronic_kidney_disease_N18)-1,
         comorb_nicotine_dependence_F17 = as.double(comorb_nicotine_dependence_F17)-1,
         comorb_heart_failure_I50 = as.double(comorb_heart_failure_I50)-1,
         comorb_ischemic_heart_disease_I20_I25 = as.double(comorb_ischemic_heart_disease_I20_I25)-1,
         comorb_lung_transplant_Z942 = as.double(comorb_lung_transplant_Z942)-1)
# a change
```

```{r}
# creates 8 new variables to generalize the comorbidity types
choc_generalized <-
  choc %>% 
  mutate(respiratory_disease = rowSums(choc[,c("comorb_bronchiectasis_J47", "comorb_copd_J40_J44", "comorb_asthma_J45", "comorb_nasal_polyps_J33", "comorb_pneumothorax_J93", "comorb_resp_failure_J96")]), cardiovascular_disease = rowSums(choc[,c("comorb_essential_hypertension_I10", "comorb_hypertensive_heart_disease_I11", "comorb_heart_failure_I50", "comorb_ischemic_heart_disease_I20_I25")]), nutrition_disease = rowSums(choc[,c("comorb_other_nutritional_deficiencies_E50_E64", "comorb_typeI_diabetes_E10", "comorb_typeII_diabetes_E11","comorb_obesity_overweight_E66", "comorb_malnutrition")]), gi_disease = rowSums(choc[,c("comorb_liver_disease_K70_K77", "comorb_other_GI_notLiver_K_excludesK70K77")]), lung_transplant = comorb_lung_transplant_Z942, nicotine_dependence = comorb_nicotine_dependence_F17, hemoptysis = comorb_hemoptysisR042, kidney_disease = comorb_chronic_kidney_disease_N18)


# Gets rid of the old "comorb" variables and leaves the 8 new generalized "comorb" vaiables
choc_generalized <- select(choc_generalized, -contains("comorb"))
```


```{r}
# general graphs to see if the new dataset is functional
```


```{r}
ggplot(choc_generalized, aes(x = respiratory_disease, fill = COVIDseverity)) + geom_bar()
```

```{r}
ggplot(choc_generalized, aes(x = cardiovascular_disease, fill = COVIDseverity)) + geom_bar()
```

```{r}
ggplot(choc_generalized, aes(x = nutrition_disease, fill = COVIDseverity)) + geom_bar(aes(y = (..count..)/sum(..count..))) + scale_y_continuous(labels = percent)
```

```{r}
ggplot(choc_generalized, aes(x = gi_disease, fill = COVIDseverity)) + geom_bar()
```

```{r}
ggplot(choc_generalized, aes(x = lung_transplant, fill = COVIDseverity)) + geom_bar()
```

```{r}
ggplot(choc_generalized, aes(x = nicotine_dependence, fill = COVIDseverity)) + geom_bar()

```

```{r}
ggplot(choc_generalized, aes(x = hemoptysis, fill = COVIDseverity)) + geom_bar()
```

```{r}

table_cardiovascular_severity <- 
  table(choc_generalized$cardiovascular_disease, choc_generalized$COVIDseverity)
table_cardiovascular_severity
```

```{r}
table_nutrition_severity <- 
  table(choc_generalized$nutrition_disease, choc_generalized$COVIDseverity)
table_nutrition_severity
```

```{r}
table_respiratory_severity <- 
  table(choc_generalized$respiratory_disease, choc_generalized$COVIDseverity)
table_respiratory_severity
```

```{r}
table_gi_severity <- 
  table(choc_generalized$gi_disease, choc_generalized$COVIDseverity)
table_gi_severity
```

```{r}
table_lung_severity <- 
  table(choc_generalized$lung_transplant, choc_generalized$COVIDseverity)
table_lung_severity
```

```{r}
table_nicotine_severity <- 
  table(choc_generalized$nicotine_dependence, choc_generalized$COVIDseverity)
table_nicotine_severity
```

```{r}
table_hemoptysis_severity <- 
  table(choc_generalized$hemoptysis, choc_generalized$COVIDseverity)
table_hemoptysis_severity
```

```{r}
table_kidney_severity <- 
  table(choc_generalized$kidney_disease, choc_generalized$COVIDseverity)
table_kidney_severity
```


```{r}
choc_disease_sum <-
  choc_generalized %>% 
  mutate(total_disease = rowSums(choc_generalized[,c("respiratory_disease", "cardiovascular_disease", "nutrition_disease", "gi_disease", "lung_transplant", "nicotine_dependence", "hemoptysis", "kidney_disease")]))
```


```{r}
choc_disease_sum %>% 
  group_by(total_disease) %>% 
  count()
```

```{r}
choc_disease_sum <-
  choc_disease_sum %>% 
  mutate(comorbs_1_2 = case_when(total_disease >= 1 & total_disease <= 2 ~ "True", total_disease > 2 | total_disease == 0 ~ "False"), comorbs_3_4 = case_when(total_disease >= 3 & total_disease <= 4 ~"True", total_disease < 3 | total_disease > 4 ~ "False"), comorbs_5_6 = case_when(total_disease >= 5 & total_disease <= 6 ~ "True", total_disease <= 5 | total_disease > 6 ~ "False"), comorbs_7_8 = case_when(total_disease >= 7 & total_disease <= 8 ~ "True", total_disease < 7 | total_disease > 8 ~ "False"), comorbs_9_10 = case_when(total_disease >= 9 & total_disease <= 10 ~ "True", total_disease < 9 | total_disease > 10 ~ "False"))
```

```{r}
choc_disease_sum %>%  
  group_by(comorbs_9_10) %>% 
  count()
```

