---
title: "hester_code"
author: "Hester Nguyen"
date: '2022-07-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
```
among pediatric patients with cystic fibrosis, how do pre-existing conditions affect the severity of COVID symptoms among this group

```{r}
head(d)
glimpse(d)

# d %>% 
#   select(personid, gender, encounterid, starts_with("comorb"),COVIDseverity) %>% 
#   mutate(has_comorb = case_when(
#      all(c('d$comorb_bronchiectasis_J47',
#              'd$comorb_copd_J40_J44',
#              'd$comorb_asthma_J45',
#              'd$comorb_nasal_polyps_J33',
#              'd$comorb_hemoptysisR042',
#              'd$comorb_pneumothorax_J93',
#              'd$comorb_resp_failure_J96',
#              'd$comorb_malnutrition',
#              'd$comorb_other_nutritional_deficiencies_E50_364',
#              'd$comorb_typeI_diabetes_E10',
#              'd$comorb_typeII_diabetes_E11',
#              'd$comorb_obesity_overweight_E66',
#              'd$comorb_liver_disease_K70_K77',
#              'd$comorb_other_GI_notLiver_K_excludesK70K77',
#              'd$comorb_essential_hypertension_I10',
#              'd$comorb_hypertensive_heart_disease_I11',
#              'd$comorb_chronic_kidney_disease_N18',
#              'd$comorb_nicotine_dependence_F17',
#              'd$comorb_heart_failure_I50',
#              'd$comorb_ischemic_heart_disease_I20_I25',
#              'd$comorb_lung_transplant_Z942'
#             )==0, na.rm = TRUE)~0,
#      any(c('d$comorb_bronchiectasis_J47',
#              'd$comorb_copd_J40_J44',
#              'd$comorb_asthma_J45',
#              'd$comorb_nasal_polyps_J33',
#              'd$comorb_hemoptysisR042',
#              'd$comorb_pneumothorax_J93',
#              'd$comorb_resp_failure_J96',
#              'd$comorb_malnutrition',
#              'd$comorb_other_nutritional_deficiencies_E50_364',
#              'd$comorb_typeI_diabetes_E10',
#              'd$comorb_typeII_diabetes_E11',
#              'd$comorb_obesity_overweight_E66',
#              'd$comorb_liver_disease_K70_K77',
#              'd$comorb_other_GI_notLiver_K_excludesK70K77',
#              'd$comorb_essential_hypertension_I10',
#              'd$comorb_hypertensive_heart_disease_I11',
#              'd$comorb_chronic_kidney_disease_N18',
#              'd$comorb_nicotine_dependence_F17',
#              'd$comorb_heart_failure_I50',
#              'd$comorb_ischemic_heart_disease_I20_I25',
#              'd$comorb_lung_transplant_Z942'
#             )==1, na.rm =TRUE)~1
#   )) 


```

```{r}
ggplot(d, 
       aes(x = age_at_encounter))+
  geom_bar( )


ggplot(d,
       aes(x = COVIDseverity, y = age_at_encounter))+
  geom_boxplot()

#age, com
```

```{r}
d %>% 
  select(personid, gender, encounterid, starts_with("comorb"),COVIDseverity) %>% 
  mutate(has_comorb = case_when(
     all(c(d$comorb_bronchiectasis_J47,
             d$comorb_copd_J40_J44,
             d$comorb_asthma_J45,
             d$comorb_nasal_polyps_J33,
             d$comorb_hemoptysisR042,
             d$comorb_pneumothorax_J93,
             d$comorb_resp_failure_J96,
             d$comorb_malnutrition,
             d$comorb_other_nutritional_deficiencies_E50_364,
             d$comorb_typeI_diabetes_E10,
             d$comorb_typeII_diabetes_E11,
             d$comorb_obesity_overweight_E66,
             d$comorb_liver_disease_K70_K77,
             d$comorb_other_GI_notLiver_K_excludesK70K77,
             d$comorb_essential_hypertension_I10,
             d$comorb_hypertensive_heart_disease_I11,
             d$comorb_chronic_kidney_disease_N18,
             d$comorb_nicotine_dependence_F17,
             d$comorb_heart_failure_I50,
             d$comorb_ischemic_heart_disease_I20_I25,
             d$comorb_lung_transplant_Z942
            )==0, na.rm = TRUE)~0,
     any(c(d$comorb_bronchiectasis_J47,
             d$comorb_copd_J40_J44,
             d$comorb_asthma_J45,
             d$comorb_nasal_polyps_J33,
             d$comorb_hemoptysisR042,
             d$comorb_pneumothorax_J93,
             d$comorb_resp_failure_J96,
             d$comorb_malnutrition,
             d$comorb_other_nutritional_deficiencies_E50_364,
             d$comorb_typeI_diabetes_E10,
             d$comorb_typeII_diabetes_E11,
             d$comorb_obesity_overweight_E66,
             d$comorb_liver_disease_K70_K77,
             d$comorb_other_GI_notLiver_K_excludesK70K77,
             d$comorb_essential_hypertension_I10,
             d$comorb_hypertensive_heart_disease_I11,
             d$comorb_chronic_kidney_disease_N18,
             d$comorb_nicotine_dependence_F17,
             d$comorb_heart_failure_I50,
             d$comorb_ischemic_heart_disease_I20_I25,
             d$comorb_lung_transplant_Z942
            )==1, na.rm =TRUE)~1
  )) %>% 
  filter(has_comorb ==1)
```

```{r}
comorb_ind <- d %>% 
  select(personid, age_at_encounter, encounterid, starts_with("comorb"),COVIDseverity) %>% 
  
    mutate(has_comorb = case_when(comorb_bronchiectasis_J47==0&
             comorb_copd_J40_J44==0&
             comorb_asthma_J45==0&
             comorb_nasal_polyps_J33==0&
             comorb_hemoptysisR042==0&
             comorb_pneumothorax_J93==0&
             comorb_resp_failure_J96==0&
             comorb_malnutrition==0&
             comorb_other_nutritional_deficiencies_E50_E64==0&
             comorb_typeI_diabetes_E10==0&
             comorb_typeII_diabetes_E11==0&
             comorb_obesity_overweight_E66==0&
             comorb_liver_disease_K70_K77==0&
             comorb_other_GI_notLiver_K_excludesK70K77==0&
             comorb_essential_hypertension_I10==0&
             comorb_hypertensive_heart_disease_I11==0&
             comorb_chronic_kidney_disease_N18==0&
             comorb_nicotine_dependence_F17==0&
             comorb_heart_failure_I50==0&
             comorb_ischemic_heart_disease_I20_I25==0&
             comorb_lung_transplant_Z942==0~0,
             comorb_bronchiectasis_J47==1|
             comorb_copd_J40_J44==1|
             comorb_asthma_J45==1|
             comorb_nasal_polyps_J33==1|
             comorb_hemoptysisR042==1|
             comorb_pneumothorax_J93==1|
             comorb_resp_failure_J96==1|
             comorb_malnutrition==1|
             comorb_other_nutritional_deficiencies_E50_E64==1|
             comorb_typeI_diabetes_E10==1|
             comorb_typeII_diabetes_E11==1|
             comorb_obesity_overweight_E66==1|
             comorb_liver_disease_K70_K77==1|
             comorb_other_GI_notLiver_K_excludesK70K77==1|
             comorb_essential_hypertension_I10==1|
             comorb_hypertensive_heart_disease_I11==1|
             comorb_chronic_kidney_disease_N18==1|
             comorb_nicotine_dependence_F17==1|
             comorb_heart_failure_I50==1|
             comorb_ischemic_heart_disease_I20_I25==1|
             comorb_lung_transplant_Z942==1
              ~1
            ))

```

```{r}
comorb_ind %>% 
  filter(has_comorb == 0) %>% 
  summary()

comorb_ind %>% 
  filter(has_comorb == 1) %>% 
  summary()

```


```{r}
comorb_ind %>% 
  ggplot(aes(x = as.factor(COVIDseverity), color = as.factor(has_comorb), fill = as.factor(has_comorb) ))+
  geom_bar()

d %>% 
  ggplot(aes(x = as.factor(COVIDseverity), color = as.factor(gender), fill = as.factor(gender)))+
  geom_bar()
```

```{r}
comorb_groups <- 
  mutate(comorb_ind,
         resp = case_when(
           comorb_copd_J40_J44 == 1|
           comorb_nasal_polyps_J33 == 1|
           comorb_pneumothorax_J93==1|
           comorb_resp_failure_J96 == 1|
           comorb_asthma_J45 == 1 |
           comorb_bronchiectasis_J47 == 1~1,
           comorb_copd_J40_J44 == 0&
           comorb_nasal_polyps_J33 == 0&
           comorb_pneumothorax_J93==0&
           comorb_resp_failure_J96 == 0&
           comorb_asthma_J45 == 0&
           comorb_bronchiectasis_J47 == 0~0
            
         ), hemoptysis = comorb_hemoptysisR042, 
         nutrition = case_when(
           comorb_typeI_diabetes_E10 == 1|
           comorb_obesity_overweight_E66 ==1|
           comorb_typeII_diabetes_E11==1|
           comorb_other_nutritional_deficiencies_E50_E64 == 1|
           comorb_malnutrition == 1~1,
           comorb_typeI_diabetes_E10 == 0&
           comorb_obesity_overweight_E66 ==0&
           comorb_typeII_diabetes_E11==0&
           comorb_other_nutritional_deficiencies_E50_E64 == 0&
           comorb_malnutrition == 0~0
         ),
         gi = case_when(
           comorb_other_GI_notLiver_K_excludesK70K77 == 1|
           comorb_liver_disease_K70_K77 == 1~1,
           comorb_other_GI_notLiver_K_excludesK70K77 == 0&
           comorb_liver_disease_K70_K77 == 0~0
         ),
         cardio = case_when(
           comorb_hypertensive_heart_disease_I11 == 1|
           comorb_essential_hypertension_I10 == 1|
           comorb_heart_failure_I50==1|
           comorb_ischemic_heart_disease_I20_I25==1~1,
           comorb_hypertensive_heart_disease_I11 == 0&
           comorb_essential_hypertension_I10 == 0&
           comorb_heart_failure_I50==0&
           comorb_ischemic_heart_disease_I20_I25==0~0
         ),
         nicotine = case_when(
           comorb_nicotine_dependence_F17 == 1~1,
           comorb_nicotine_dependence_F17== 0~0
           
         ), 
         kidney = case_when(
           comorb_chronic_kidney_disease_N18 == 1~1,
           comorb_chronic_kidney_disease_N18 == 0~0
         ),
         lung_trans = case_when(
           comorb_lung_transplant_Z942 == 1~1, 
           comorb_lung_transplant_Z942 == 0~0
         )
         ) %>% 
  select(-starts_with('comorb'))
comorb_groups


```

```{r}
comorb_type <-
  mutate(comorb_groups,comorb_types = case_when(
    scomorb_J == 1~'J',
    scomorb_mal ==1~'mal',
    scomorb_E==1~'E',
    scomorb_K ==1 ~'K',
    scomorb_I == 1~'I',
    scomorb_F == 1 ~'F',
    scomorb_N == 1 ~'N',
    scomorb_Z ==1 ~"Z",
    TRUE ~ 'None'

  ))
comorb_type

```


```{r}


comorb_type %>%
  ggplot(aes(x = as.factor(COVIDseverity), color = as.factor(comorb_types), fill = as.factor(comorb_types)))+
  geom_bar()


j_plot <- comorb_groups %>% 
  filter(scomorb_J ==1)%>% 
  ggplot(aes(x = as.factor(COVIDseverity)))+
  geom_bar()

mal_plot <- comorb_groups %>% 
  filter(scomorb_mal ==1) %>% 
  ggplot(aes(x = as.factor(COVIDseverity)))+
  geom_bar()

e_plot <- comorb_groups %>% 
  filter(scomorb_E ==1)%>% 
  ggplot(aes(x = as.factor(COVIDseverity)))+
  geom_bar()

k_plot <- comorb_groups %>% 
  filter(scomorb_K ==1)%>% 
  ggplot(aes(x = as.factor(COVIDseverity)))+
  geom_bar()

i_plot <- comorb_groups %>% 
  filter(scomorb_I ==1)%>% 
  ggplot(aes(x = as.factor(COVIDseverity)))+
  geom_bar()

f_plot <- comorb_groups %>% 
  filter(scomorb_F ==1)%>% 
  ggplot(aes(x = as.factor(COVIDseverity)))+
  geom_bar()

n_plot <- comorb_groups %>% 
  filter(scomorb_N ==1)%>% 
  ggplot(aes(x = as.factor(COVIDseverity)))+
  geom_bar()

z_plot <- comorb_groups %>% 
  filter(scomorb_Z ==1) %>% 
  ggplot(aes(x = as.factor(COVIDseverity)))+
  geom_bar()

library(gridExtra)
library(cowplot)
plot_grid(j_plot, mal_plot, e_plot, k_plot, i_plot, f_plot, n_plot, z_plot,labels = c('j_plot', 'mal_plot', 'e_plot', 'k_plot', 'i_plot', 'f_plot', 'n_plot', 'z_plot'), ncol = 8, rel_widths = 5)



# ggplot(combined_comorb_data,
#        aes(x = COVIDseverity))+
#   geom_bar()

# comorb_groups %>% 
#   filter(comorb_type =='None') %>% 
#   ggplot(aes(x = as.factor(COVIDseverity)))+
#   geom_bar()
```


```{r}
comorb_type %>% 
  ggplot(aes(x = as.factor(COVIDseverity), y = age_at_encounter, color = as.factor(comorb_types), fill = as.factor(comorb_types)))+
  geom_boxplot()
  
```



```{r}
comorb_data <- data.frame("Covid_severity" = c(0, 1, 2,0, 1, 2,0, 1),
                          "Comorbidity" = c("resp",
    "nutrition",
    "hemoptysis",
    "gi" ,
    "cardio",
    "nicotine", 
    "kidney", 
    "lung_trans"
    )
)


conTable = table(comorb_data)
print(conTable)

a_matrix= matrix(c(comorb_groups %>%
  filter(COVIDseverity == 0 & nutrition == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 1 & nutrition == 1) %>%
  nrow()  ,comorb_groups %>%
  filter(COVIDseverity == 2 & nutrition == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 0 & nicotine == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 1 & nicotine == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 2 & nicotine == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 0 & cardio == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 1 & cardio == 1) %>%
  nrow(), comorb_groups %>%
  filter(COVIDseverity == 2 & cardio == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 0 & resp == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 1 & resp == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 2 & resp == 1) %>%
  nrow(), comorb_groups %>%
  filter(COVIDseverity == 0 & gi == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 1 & gi == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 2 & gi == 1) %>%
  nrow(), comorb_groups %>%
  filter(COVIDseverity == 0 & hemoptysis == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 1 & hemoptysis == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 2 & hemoptysis == 1) %>%
  nrow(), comorb_groups %>%
  filter(COVIDseverity == 0 & kidney == 1) %>%
  nrow(), comorb_groups %>%
  filter(COVIDseverity == 1 & kidney == 1) %>%
  nrow(), comorb_groups %>%
  filter(COVIDseverity == 2 & kidney == 1) %>%
  nrow(), comorb_groups %>%
  filter(COVIDseverity == 0 & lung_trans == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 1 & lung_trans == 1) %>%
  nrow(),comorb_groups %>%
  filter(COVIDseverity == 2 & lung_trans == 1) %>%
  nrow()),nrow =3, ncol= 8)


chisq.test(a_matrix)
#a_matrix <- matrix(c())


conTable[1,1] = comorb_groups %>% 
  filter(COVIDseverity == 0 & cardio == 1) %>% 
  nrow()

conTable[2,1] = comorb_groups %>% 
  filter(COVIDseverity == 1 & cardio == 1) %>% 
  nrow()  

conTable[3,1] = comorb_groups %>% 
  filter(COVIDseverity == 2 & cardio== 1) %>% 
  nrow()

conTable[1,2] = comorb_groups %>% 
  filter(COVIDseverity == 0 & gi == 1) %>% 
  nrow()

conTable[2,2] = comorb_groups %>% 
  filter(COVIDseverity == 1 & gi== 1) %>% 
  nrow()

conTable[3,2]= comorb_groups %>% 
  filter(COVIDseverity == 2 & gi == 1) %>% 
  nrow()

conTable[1,3]= comorb_groups %>% 
  filter(COVIDseverity == 0 & hemoptysis == 1) %>% 
  nrow()

conTable[2,3] = comorb_groups %>% 
  filter(COVIDseverity == 1 & hemoptysis == 1) %>% 
  nrow()

conTable[3,3] = comorb_groups %>% 
  filter(COVIDseverity == 2 & hemoptysis == 1) %>% 
  nrow()

conTable[1,4]= comorb_groups %>% 
  filter(COVIDseverity == 0 & kidney == 1) %>% 
  nrow()

conTable[2,4]= comorb_groups %>% 
  filter(COVIDseverity == 1 & kidney == 1) %>% 
  nrow()

conTable[3,4]= comorb_groups %>% 
  filter(COVIDseverity == 2 & kidney == 1) %>% 
  nrow()

conTable[1,5]= comorb_groups %>% 
  filter(COVIDseverity == 0 & lung_trans == 1) %>% 
  nrow()

conTable[2,5]= comorb_groups %>% 
  filter(COVIDseverity == 1 & lung_trans == 1) %>% 
  nrow()

conTable[3,5]= comorb_groups %>% 
  filter(COVIDseverity == 2 & lung_trans == 1) %>% 
  nrow()

conTable[1,6]= comorb_groups %>% 
  filter(COVIDseverity == 0 & nicotine == 1) %>% 
  nrow()

conTable[2,6]= comorb_groups %>% 
  filter(COVIDseverity == 1 & nicotine == 1) %>% 
  nrow()

conTable[3,6]= comorb_groups %>% 
  filter(COVIDseverity == 2 & nicotine == 1) %>% 
  nrow()

conTable[1,7]= comorb_groups %>% 
  filter(COVIDseverity == 0 & nutrition == 1) %>% 
  nrow()

conTable[2,7]= comorb_groups %>% 
  filter(COVIDseverity == 1 & nutrition == 1) %>% 
  nrow()

conTable[3,7]= comorb_groups %>% 
  filter(COVIDseverity == 2 & nutrition == 1) %>% 
  nrow()

conTable[1,8]= comorb_groups %>% 
  filter(COVIDseverity == 0 & resp == 1) %>% 
  nrow()

conTable[2,8]= comorb_groups %>% 
  filter(COVIDseverity == 1 & resp == 1) %>% 
  nrow()

conTable[3,8]= comorb_groups %>% 
  filter(COVIDseverity == 2 & resp == 1) %>% 
  nrow()

conTable
conTable_totals<- addmargins(conTable,c(1,2))
#chisq.test(conTable)

conTable
```

```{r}

con_table_df <- data.frame(conTable)

ggplot(data = con_table_df, aes(x = Comorbidity, y = Freq, fill = Covid_severity))+
  geom_bar(stat = "identity", position = position_dodge(), alpha = 0.75)+
  ylim(0,3000) +
  geom_text(aes(label = Freq), fontface = "bold", vjust = 1.5,
            position = position_dodge(.9), size = 4)+
  labs(x = "\n Comorbities", y = "Frequency\n", title = "\n Covid Severity level based on Comorbidities \n")+
  theme(plot.title = element_text(hjust = 0.5), 
        axis.title.x = element_text(face = "bold", colour = "green", size = 12),
        axis.title.y = element_text(face = "bold", colour = "green", size = 12),
        legend.title = element_text(face = "bold", size = 10))+
  scale_fill_discrete(name = 'COVID Severity', labels = c('Mild', 'Moderate', 'Severe'))

```

```{r}
ggplot(data = con_table_df, aes(x = Comorbidity, y = comorb_groups$age_at_encounter, fill = Covid_severity))+
  geom_boxplot(stat = "identity", position = position_dodge(), alpha = 0.75)+
  ylim(0,3000) +
  geom_text(aes(label = comorb_groups$age_at_encounter), fontface = "bold", vjust = 1.5,
            position = position_dodge(.9), size = 4)+
  labs(x = "\n Comorbities", y = "age\n", title = "\n Covid Severity level based on Comorbidities \n")+
  theme(plot.title = element_text(hjust = 0.5), 
        axis.title.x = element_text(face = "bold", colour = "green", size = 12),
        axis.title.y = element_text(face = "bold", colour = "green", size = 12),
        legend.title = element_text(face = "bold", size = 10))
```


```{r}
choc <- d %>% 
  mutate(comorb_bronchiectasis_J47 = as.double(comorb_bronchiectasis_J47)-1,
         comorb_copd_J40_J44 = as.double(comorb_copd_J40_J44)-1,
         comorb_asthma_J45 = as.double(comorb_asthma_J45)-1,
         comorb_nasal_polyps_J33 = as.double(comorb_nasal_polyps_J33)-1,
         comorb_hemoptysisR042 = as.double(comorb_hemoptysisR042)-1,
         comorb_pneumothorax_J93 = as.double(comorb_pneumothorax_J93)-1,
         comorb_resp_failure_J96 = as.double(comorb_resp_failure_J96)-1,
         comorb_malnutrition = as.double(comorb_malnutrition)-1,
         comorb_other_nutritional_deficiencies_E50_E64 = as.double(comorb_other_nutritional_deficiencies_E50_E64)-1,
         comorb_typeI_diabetes_E10 = as.double(comorb_typeI_diabetes_E10)-1,
         comorb_typeII_diabetes_E11 = as.double(comorb_typeII_diabetes_E11)-1,
         comorb_obesity_overweight_E66 = as.double(comorb_obesity_overweight_E66)-1,
         comorb_liver_disease_K70_K77 = as.double(comorb_liver_disease_K70_K77)-1,
         comorb_other_GI_notLiver_K_excludesK70K77 = as.double(comorb_other_GI_notLiver_K_excludesK70K77)-1,
         comorb_essential_hypertension_I10 = as.double(comorb_essential_hypertension_I10)-1,
         comorb_hypertensive_heart_disease_I11 = as.double(comorb_hypertensive_heart_disease_I11)-1,
         comorb_chronic_kidney_disease_N18 = as.double(comorb_chronic_kidney_disease_N18)-1,
         comorb_nicotine_dependence_F17 = as.double(comorb_nicotine_dependence_F17)-1,
         comorb_heart_failure_I50 = as.double(comorb_heart_failure_I50)-1,
         comorb_ischemic_heart_disease_I20_I25 = as.double(comorb_ischemic_heart_disease_I20_I25)-1,
         comorb_lung_transplant_Z942 = as.double(comorb_lung_transplant_Z942)-1)
```


```{r}

choc_generalized <-
  choc %>% 
  mutate(respiratory_disease = rowSums(choc[,c("comorb_bronchiectasis_J47", "comorb_copd_J40_J44", "comorb_asthma_J45", "comorb_nasal_polyps_J33", "comorb_pneumothorax_J93", "comorb_resp_failure_J96")]), cardiovascular_disease = rowSums(choc[,c("comorb_essential_hypertension_I10", "comorb_hypertensive_heart_disease_I11", "comorb_heart_failure_I50", "comorb_ischemic_heart_disease_I20_I25")]), nutrition_disease = rowSums(choc[,c("comorb_other_nutritional_deficiencies_E50_E64", "comorb_typeI_diabetes_E10", "comorb_typeII_diabetes_E11","comorb_obesity_overweight_E66", "comorb_malnutrition")]), gi_disease = rowSums(choc[,c("comorb_liver_disease_K70_K77", "comorb_other_GI_notLiver_K_excludesK70K77")]), lung_transplant = comorb_lung_transplant_Z942, nicotine_dependence = comorb_nicotine_dependence_F17, hemoptysis = comorb_hemoptysisR042, kidney_disease = comorb_chronic_kidney_disease_N18)
choc_generalized <- select(choc_generalized, -contains("comorb"))





 sum_disease_type_matrix = matrix(c(sum(choc_generalized$cardiovascular_disease[choc_generalized$COVIDseverity == 0]),
                                    sum(choc_generalized$cardiovascular_disease[choc_generalized$COVIDseverity == 1]),
                                    sum(choc_generalized$cardiovascular_disease[choc_generalized$COVIDseverity == 2]),
                                    sum(choc_generalized$gi_disease[choc_generalized$COVIDseverity == 0]),
                                    sum(choc_generalized$gi_disease[choc_generalized$COVIDseverity == 1]),
                                    sum(choc_generalized$gi_disease[choc_generalized$COVIDseverity == 2]),
                                    sum(choc_generalized$hemoptysis[choc_generalized$COVIDseverity == 0]),
                                    sum(choc_generalized$hemoptysis[choc_generalized$COVIDseverity == 1]),
                                    sum(choc_generalized$hemoptysis[choc_generalized$COVIDseverity == 2]),
                                    sum(choc_generalized$kidney_disease[choc_generalized$COVIDseverity == 0]),
                                    sum(choc_generalized$kidney_disease[choc_generalized$COVIDseverity == 1]),
                                    sum(choc_generalized$kidney_disease[choc_generalized$COVIDseverity == 2]),
                                    sum(choc_generalized$lung_transplant[choc_generalized$COVIDseverity == 0]),
                                    sum(choc_generalized$lung_transplant[choc_generalized$COVIDseverity == 1]),
                                    sum(choc_generalized$lung_transplant[choc_generalized$COVIDseverity == 2]),
                                    sum(choc_generalized$nicotine_dependence[choc_generalized$COVIDseverity == 0]),
                                    sum(choc_generalized$nicotine_dependence[choc_generalized$COVIDseverity == 1]),
                                    sum(choc_generalized$nicotine_dependence[choc_generalized$COVIDseverity == 2]),
                                    sum(choc_generalized$nutrition_disease[choc_generalized$COVIDseverity == 0]),
                                    sum(choc_generalized$nutrition_disease[choc_generalized$COVIDseverity == 1]),
                                    sum(choc_generalized$nutrition_disease[choc_generalized$COVIDseverity == 2]),
                                    sum(choc_generalized$respiratory_disease[choc_generalized$COVIDseverity == 0]),
                                    sum(choc_generalized$respiratory_disease[choc_generalized$COVIDseverity == 1]),
                                    sum(choc_generalized$respiratory_disease[choc_generalized$COVIDseverity == 2])
                                    ), nrow = 3, ncol = 8, dimnames = list(Covid_severity = c(0,1,2), Comorbidities = c('cardiovascular', 'gi','hemoptysis', 'kidney', 'lung_transplant', 'nicotine', 'nutrition', 'respiratory')))
 
 heatmap(sum_disease_type_matrix, main = 'Types of Comorbidity Significance', xlab = 'Comorbidities', ylab = 'Covid Severity Level', margins = c(10,4))
                                        
                                        
   
```


```{r}
#comorb_data <- data.frame("Covid_severity" = c(0, 1, 2,0, 1, 2,0, 1),
                          "Comorbidity" = c('None', 'Has_comorb')
    
#)

a_matrix = matrix(c(comorb_groups %>% 
                      filter(COVIDseverity == 0& has_comorb==1) %>% 
                      nrow(),
                    comorb_groups %>% 
                      filter(COVIDseverity == 1& has_comorb==1) %>% 
                      nrow(),
                    comorb_groups %>% 
                      filter(COVIDseverity == 2& has_comorb==1) %>% 
                      nrow(),
                    comorb_groups %>% 
                      filter(COVIDseverity == 0& has_comorb==0) %>% 
                      nrow(),
                    comorb_groups %>% 
                      filter(COVIDseverity == 1& has_comorb==0) %>% 
                      nrow(),
                    comorb_groups %>% 
                      filter(COVIDseverity == 2& has_comorb==0) %>% 
                      nrow()), nrow =3, ncol =2, dimnames = list(Covid_severity = c(0,1,2),Has_comorb = c(1,0)))

#/4957
#/4380
a_matrix
chisq.test(a_matrix)
#addmargins(a_matrix,c(1,2))
a_matrix.prop <- matrix(c(a_matrix[1,1]/4957,a_matrix[2,1]/4957, a_matrix[3,1]/4957,
                          a_matrix[1,2]/4380, a_matrix[2,2]/4380, a_matrix[3,2]/4380
                          ), nrow =3, ncol = 2, dimnames = list(Covid_severity = c(0,1,2), Has_comorb = c(1,0)))
a_matrix.prop
conTable = table(comorb_data)
```

```{r}
choc_disease_sum <-
  choc_generalized %>% 
  mutate(total_disease = rowSums(choc_generalized[,c("respiratory_disease", "cardiovascular_disease", "nutrition_disease", "gi_disease", "lung_transplant", "nicotine_dependence", "hemoptysis", "kidney_disease")]))

choc_disease_sum <-
  choc_disease_sum %>% 
  mutate(comorbs_0 = case_when(total_disease == 0 ~TRUE, total_disease != 0 ~FALSE),comorbs_1_2 = case_when(total_disease >= 1 & total_disease <= 2 ~ TRUE, total_disease > 2 | total_disease == 0 ~ FALSE), comorbs_3_4 = case_when(total_disease >= 3 & total_disease <= 4 ~TRUE, total_disease < 3 | total_disease > 4 ~ FALSE), comorbs_5_6 = case_when(total_disease >= 5 & total_disease <= 6 ~ TRUE, total_disease <= 5 | total_disease > 6 ~ FALSE), comorbs_7_8 = case_when(total_disease >= 7 & total_disease <= 8 ~ TRUE, total_disease < 7 | total_disease > 8 ~ FALSE), comorbs_9_10 = case_when(total_disease >= 9 & total_disease <= 10 ~ TRUE, total_disease < 9 | total_disease > 10 ~ FALSE))

choc_disease_sum_matrix <- matrix(c(
  choc_disease_sum %>% 
  filter(comorbs_0  & COVIDseverity==0 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_0  & COVIDseverity==1 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_0  & COVIDseverity==2 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_1_2  & COVIDseverity==0 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_1_2  & COVIDseverity==1)%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_1_2  & COVIDseverity==2 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_3_4  & COVIDseverity==0 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_3_4  & COVIDseverity==1 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_3_4  & COVIDseverity==2 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_5_6  & COVIDseverity==0 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_5_6  & COVIDseverity==1 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_5_6  & COVIDseverity==2 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_7_8  & COVIDseverity==0 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_7_8  & COVIDseverity==1 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_7_8  & COVIDseverity==2)%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_9_10  & COVIDseverity==0 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_9_10  & COVIDseverity==1 )%>% 
  nrow(),
  choc_disease_sum %>% 
  filter(comorbs_9_10  & COVIDseverity==2 )%>% 
  nrow()), nrow = 3, ncol = 6, dimnames= list(Covid_severity = c(0,1,2), Number_of_comorbidities = c('0', '1-2', '3-4', '5-6', '7-8', '9-10')))
  
  choc_disease_sum_matrix
  addmargins(choc_disease_sum_matrix, c(1,2))
  
  choc_disease_sum_matrix.prop <- matrix(c(choc_disease_sum_matrix[1,1]/4380,choc_disease_sum_matrix[2,1]/4380,choc_disease_sum_matrix[3,1]/4380,
         choc_disease_sum_matrix[1,2]/3644,choc_disease_sum_matrix[2,2]/3644, choc_disease_sum_matrix[3,2]/3644,
         choc_disease_sum_matrix[1,3]/908,choc_disease_sum_matrix[2,3]/908, choc_disease_sum_matrix[3,3]/908,
         choc_disease_sum_matrix[1,4]/275,choc_disease_sum_matrix[2,4]/275, choc_disease_sum_matrix[3,4]/275,
         choc_disease_sum_matrix[1,5]/110,choc_disease_sum_matrix[2,5]/110, choc_disease_sum_matrix[3,5]/110,
         choc_disease_sum_matrix[1,6]/20,choc_disease_sum_matrix[2,6]/20,choc_disease_sum_matrix[3,6]/20), nrow = 3, ncol = 6, dimnames= list(Covid_severity = c(0,1,2), Number_of_comorbidities = c('0', '1-2', '3-4', '5-6', '7-8', '9-10')))
choc_disease_sum_matrix.prop
  
  chisq.test(choc_disease_sum_matrix)
  # choc_disease_sum$comorbs_0[choc_disease_sum$COVIDseverity==0]==TRUE),
  #                                   choc_disease_sum$comorbs_0[choc_disease_sum$COVIDseverity==1],
  #                                   choc_disease_sum$comorbs_0[choc_disease_sum$COVIDseverity==2],
  #                                   choc_disease_sum$comorbs_1_2[choc_disease_sum$COVIDseverity==0],
  #                                   choc_disease_sum$comorbs_1_2[choc_disease_sum$COVIDseverity==1],
  #                                   choc_disease_sum$comorbs_1_2[choc_disease_sum$COVIDseverity==2],
  #                                   choc_disease_sum$comorbs_3_4[choc_disease_sum$COVIDseverity==0],
  #                                   choc_disease_sum$comorbs_3_4[choc_disease_sum$COVIDseverity==1],
  #                                   choc_disease_sum$comorbs_3_4[choc_disease_sum$COVIDseverity==2],
  #                                   choc_disease_sum$comorbs_5_6[choc_disease_sum$COVIDseverity==0],
  #                                   choc_disease_sum$comorbs_5_6[choc_disease_sum$COVIDseverity==1],
  #                                   choc_disease_sum$comorbs_5_6[choc_disease_sum$COVIDseverity==2],
  #                                   choc_disease_sum$comorbs_7_8[choc_disease_sum$COVIDseverity==0],
  #                                   choc_disease_sum$comorbs_7_8[choc_disease_sum$COVIDseverity==1],
  #                                   choc_disease_sum$comorbs_7_8[choc_disease_sum$COVIDseverity==2],
  #                                   choc_disease_sum$comorbs_9_10[choc_disease_sum$COVIDseverity==0],
  #                                   choc_disease_sum$comorbs_9_10[choc_disease_sum$COVIDseverity==1],
  #                                   choc_disease_sum$comorbs_9_10[choc_disease_sum$COVIDseverity==2]
  #                                   ), nrow = 3, ncol = 6, dimnames= list(Covid_severity = c(0,1,2), Number_of_comorbidities = c('0', '1-2', '3-4', '5-6', '7-8', '9_10')))
```

```{r}
choc_disease_sum <- 
  mutate(choc_disease_sum, count_num = case_when(total_disease ==0 & COVIDseverity ==0~nrow(filter(choc_disease_sum, total_disease ==0 & COVIDseverity ==0)),
                                             total_disease ==0 & COVIDseverity ==1~nrow(filter(choc_disease_sum, total_disease ==0 & COVIDseverity ==1)),
                                             total_disease ==0 & COVIDseverity ==2~nrow(filter(choc_disease_sum, total_disease ==0 & COVIDseverity ==2)),
                                             total_disease >=1 & total_disease<=2  & COVIDseverity ==0~nrow(filter(choc_disease_sum, total_disease >=1 & total_disease<=2 & COVIDseverity ==0)),
                                             total_disease >=1 & total_disease<=2  & COVIDseverity ==1~nrow(filter(choc_disease_sum, total_disease >=1 & total_disease<=2 & COVIDseverity ==1)),
                                             total_disease >=1 & total_disease<=2  & COVIDseverity ==2~nrow(filter(choc_disease_sum, total_disease >=1 & total_disease<=2 & COVIDseverity ==2)),
                                             total_disease >=3 & total_disease<=4  & COVIDseverity ==0~nrow(filter(choc_disease_sum, total_disease >=3 & total_disease<=4 & COVIDseverity ==0)),
                                             total_disease >=3 & total_disease<=4  & COVIDseverity ==1~nrow(filter(choc_disease_sum, total_disease >=3 & total_disease<=4 & COVIDseverity ==1)),
                                             total_disease >=3 & total_disease<=4  & COVIDseverity ==2~nrow(filter(choc_disease_sum, total_disease >=3 & total_disease<=4 & COVIDseverity ==2)),
                                             total_disease >=5 & total_disease<=6  & COVIDseverity ==0~nrow(filter(choc_disease_sum, total_disease >=5 & total_disease<=6 & COVIDseverity ==0)),
                                             total_disease >=5 & total_disease<=6  & COVIDseverity ==1~nrow(filter(choc_disease_sum, total_disease >=5 & total_disease<=6 & COVIDseverity ==1)),
                                             total_disease >=5 & total_disease<=6  & COVIDseverity ==2~nrow(filter(choc_disease_sum, total_disease >=5 & total_disease<=6 & COVIDseverity ==2)),
                                             total_disease >=7 & total_disease<=8  & COVIDseverity ==0~nrow(filter(choc_disease_sum, total_disease >=7 & total_disease<=8 & COVIDseverity ==0)),
                                             total_disease >=7 & total_disease<=8  & COVIDseverity ==1~nrow(filter(choc_disease_sum, total_disease >=7 & total_disease<=8 & COVIDseverity ==1)),
                                             total_disease >=7 & total_disease<=8  & COVIDseverity ==2~nrow(filter(choc_disease_sum, total_disease >=7 & total_disease<=8 & COVIDseverity ==2)),
                                             total_disease >=9 & total_disease<=10  & COVIDseverity ==0~nrow(filter(choc_disease_sum, total_disease >=9 & total_disease<=10 & COVIDseverity ==0)),
                                             total_disease >=9 & total_disease<=10  & COVIDseverity ==1~nrow(filter(choc_disease_sum, total_disease >=9 & total_disease<=10 & COVIDseverity ==1)),
                                             total_disease >=9 & total_disease<=10  & COVIDseverity ==2~nrow(filter(choc_disease_sum, total_disease >=9 & total_disease<=10 & COVIDseverity ==2))
                                       
                                             ))
ggplot(choc_disease_sum, aes(x = total_disease,y = count_num, color = COVIDseverity,fill = COVIDseverity))+
  geom_point() +
  geom_line()
```

```{r}
age_group <- 
  mutate(comorb_groups, age_0_6 = case_when(age_at_encounter <7 ~TRUE, TRUE~FALSE),
         age_7_17 = case_when(age_at_encounter>6 & age_at_encounter <18~TRUE, TRUE~FALSE),
         age_18_25 = case_when(age_at_encounter>17~TRUE, TRUE~FALSE))
age_group


a_func <- function(comorbd, person_num){
  comorb_vect <- c()
  #print(person_num)
  #print('h',comorb_vect)
    if(any(comorbd[comorbd$encounterid == person_num, ]$resp==1)){
      comorb_vect <- append(comorb_vect, 'resp')
    }
    if(any(comorbd[comorbd$encounterid == person_num, ]$hemoptysis==1)){
      comorb_vect <- append(comorb_vect, 'hemoptysis')
    }
    if(any(comorbd[comorbd$encounterid == person_num, ]$nutrition ==1)){
      comorb_vect <- append(comorb_vect, 'nutrition')
    }
    if(any(comorbd[comorbd$encounterid == person_num, ]$gi == 1)){
      comorb_vect <- append(comorb_vect, 'gi')
    }
    if(any(comorbd[comorbd$encounterid == person_num, ]$cardio==1)){
      comorb_vect <- append(comorb_vect, 'cardio')
    }
    if(any(comorbd[comorbd$encounterid == person_num, ]$kidney==1)){
      comorb_vect <- append(comorb_vect, 'kidney')
    }
    if(any(comorbd[comorbd$encounterid == person_num, ]$lung_trans == 1)){
      comorb_vect <- append(comorb_vect, 'lung_trans')
    }
    if(any(comorbd[comorbd$encounterid == person_num, ]$nicotine==1)){
      comorb_vect <- append(comorb_vect, 'nicotine')
    }
    #print('e',comorb_vect)
    return(paste(comorb_vect, collapse= ", "))
}



age_group <- 
  mutate(comorb_groups, age_grp = case_when(age_at_encounter <7 ~'[0,6]', 
                                        age_at_encounter >6 & age_at_encounter <18~'[7,17]',
                                        age_at_encounter>17~'[18,25]')) %>% 
  mutate(age_grp = as.factor(age_grp)) %>% 
  mutate(comorb_type = case_when(has_comorb==1~a_func(comorb_groups, encounterid)
                                   ))

  # c(case_when(resp ==1~TRUE, TRUE~FALSE),
  #                                    case_when(hemoptysis == 1~TRUE, TRUE~FALSE),
  #                                    case_when(nutrition ==1~TRUE, TRUE~FALSE),
  #                                    case_when(gi==1~TRUE, TRUE~FALSE),
  #                                    case_when(cardio==1~TRUE, TRUE~FALSE),
  #                                    case_when(kidney ==1~TRUE, TRUE~FALSE),
  #                                    case_when(lung_trans ==1 ~TRUE, TRUE~FALSE),
  #                                    case_when(nicotine==1~TRUE, TRUE~FALSE))}

#resp == 1 | hemopytsis == 1 | nutition ==1 | gi ==1 | cardio ==1 | kidney ==1 | lung_trans ==1 | nicotine ==1
# resp == 1 & hemopytsis == 1 & nutition ==1 & gi ==1 & cardio ==1 & kidney ==1 & lung_trans ==1 & nicotine ==1 ~ c('resp','hemopytsis', 'nutition', 'gi', 'cardio', 'kidney', 'lung_trans', 'nicotine'),
#                                  resp == 1 & hemopytsis == 1 & nutition ==1 & gi ==1 & cardio ==1 & kidney ==1 & nicotine ==1 ~ c('resp','hemopytsis', 'nutition', 'gi', 'cardio', 'kidney', 'nicotine'),
#                                  resp == 1 & hemopytsis == 1 & nutition ==1 & gi ==1 & cardio ==1 & lung_trans ==1& nicotine ==1~c('resp','hemopytsis', 'nutition', 'gi', 'cardio',  'lung_trans', 'nicotine'),
#                                  resp == 1 & hemopytsis == 1 & nutition ==1 & gi ==1  & kidney ==1 & lung_trans ==1& nicotine ==1~ c('resp','hemopytsis', 'nutition', 'gi',  'kidney', 'lung_trans', 'nicotine'),
#                                  resp == 1 & hemopytsis == 1 & nutition ==1 & cardio ==1 & kidney ==1 & lung_trans ==1& nicotine ==1 ~ c('resp','hemopytsis', 'nutition', 'cardio', 'kidney', 'lung_trans', 'nicotine'),
#                                  resp == 1 & hemopytsis == 1 & gi ==1 & cardio ==1 & kidney ==1 & lung_trans ==1& nicotine ==1 ~ c('resp','hemopytsis', 'gi', 'cardio', 'kidney', 'lung_trans', 'nicotine'),
#                                  resp == 1 & nutition ==1 & gi ==1 & cardio ==1 & kidney ==1 & lung_trans ==1& nicotine ==1 ~ c('resp', 'nutition', 'gi', 'cardio', 'kidney', 'lung_trans', 'nicotine'),
#                                  hemopytsis == 1 & nutition ==1 & gi ==1 & cardio ==1 & kidney ==1 & lung_trans ==1& nicotine ==1 ~ c('hemopytsis', 'nutition', 'gi', 'cardio', 'kidney', 'lung_trans', 'nicotine'),
#                                  resp == 1 & hemopytsis == 1 & nutition ==1 & gi ==1 & cardio ==1 & kidney ==1 & lung_trans ==1 ~c('resp','hemopytsis', 'nutition', 'gi', 'cardio', 'kidney', 'lung_trans')
age_group



```

```{r}
#ggplot(age_group,
       #aes(x = age_grp, y= ))


an_func <- function(a_data, id){
  a_num <- a_data %>% 
    filter(personid == id) %>% 
    nrow()
  return(a_num)
}


```

```{r}
choc <- d %>% 
  mutate(
        comorb_bronchiectasis_J47 = as.integer(comorb_bronchiectasis_J47)-1,
        comorb_copd_J40_J44 = as.integer(comorb_copd_J40_J44)-1,
        comorb_asthma_J45 = as.integer(comorb_asthma_J45)-1,
        comorb_nasal_polyps_J33 = as.integer(comorb_nasal_polyps_J33)-1,
        comorb_hemoptysisR042 = as.integer(comorb_hemoptysisR042)-1,
        comorb_pneumothorax_J93 = as.integer(comorb_pneumothorax_J93)-1,
        comorb_resp_failure_J96 = as.integer(comorb_resp_failure_J96)-1,
        comorb_malnutrition = as.integer(comorb_malnutrition)-1,
        comorb_other_nutritional_deficiencies_E50_E64 = as.integer(comorb_other_nutritional_deficiencies_E50_E64)-1,
        comorb_typeI_diabetes_E10 = as.integer(comorb_typeI_diabetes_E10)-1,
        comorb_typeII_diabetes_E11 = as.integer(comorb_typeII_diabetes_E11)-1,
        comorb_obesity_overweight_E66 = as.integer(comorb_obesity_overweight_E66)-1,
        comorb_liver_disease_K70_K77 = as.integer(comorb_liver_disease_K70_K77)-1,
        comorb_other_GI_notLiver_K_excludesK70K77 = as.integer(comorb_other_GI_notLiver_K_excludesK70K77)-1,
        comorb_essential_hypertension_I10 = as.integer(comorb_essential_hypertension_I10)-1,
        comorb_hypertensive_heart_disease_I11 = as.integer(comorb_hypertensive_heart_disease_I11)-1,
        comorb_chronic_kidney_disease_N18 = as.integer(comorb_chronic_kidney_disease_N18)-1,
        comorb_nicotine_dependence_F17 = as.integer(comorb_nicotine_dependence_F17)-1,
        comorb_heart_failure_I50 = as.integer(comorb_heart_failure_I50)-1,
        comorb_ischemic_heart_disease_I20_I25 = as.integer(comorb_ischemic_heart_disease_I20_I25)-1,
        comorb_lung_transplant_Z942 = as.integer(comorb_lung_transplant_Z942)-1,
        
        )

choc <- choc %>% 
  mutate(
    total_comorb = rowSums(choc[,15:35]),
    servicedate = as.Date(choc[,9]),
    dischargedate = as.Date(choc[,10])
  )

care_time <- as.numeric(difftime(choc$dischargedate, choc$servicedate, units = "days"))

choc <- choc %>% 
  mutate(care_time = care_time)


```

```{r}
#library(glmnet)
library(dplyr)
library(tidyverse)
choc_by_visit <- choc %>% 
  group_by(personid) %>% 
  mutate(visit =1:n())
  
 # group_by(personid, servicedate) %>% 
 #  arrange(personid, servicedate) %>% 
 #  ungroup() %>% 
 #  group_by(personid) %>% 
 #  mutate(visit = n())


library(ordinal)
a.model <- clmm2(COVIDseverity~ care_time + age_at_encounter+
                   as.factor(comorb_bronchiectasis_J47)+
                   as.factor(comorb_asthma_J45)+as.factor(comorb_resp_failure_J96)+
                   as.factor(comorb_other_nutritional_deficiencies_E50_E64)+
                   as.factor(comorb_typeII_diabetes_E11)+as.factor(comorb_liver_disease_K70_K77)+
                   as.factor(comorb_essential_hypertension_I10)+
                   as.factor(comorb_chronic_kidney_disease_N18)+as.factor(comorb_heart_failure_I50)+
                   as.factor(comorb_lung_transplant_Z942)+
                   as.factor(comorb_ischemic_heart_disease_I20_I25)+
                   as.factor(comorb_nicotine_dependence_F17)+as.factor(comorb_hypertensive_heart_disease_I11)+
                   as.factor(comorb_other_GI_notLiver_K_excludesK70K77)+
                   as.factor(comorb_obesity_overweight_E66)+as.factor(comorb_typeI_diabetes_E10)+
                   as.factor(comorb_malnutrition)+as.factor(comorb_pneumothorax_J93)+
                   as.factor(comorb_nasal_polyps_J33)+as.factor(comorb_copd_J40_J44)+
                   +INOTROPES+REMDESIVIR+CCP+DEXAMETHASONE+ENOXAPARIN+HEPARIN+IVIG+METHYLPREDNISOLONE+TOCILIZUMAB+ASPIRIN, data = choc_by_visit)
head(another_choc)

  
grid <- 10^seq(10, -2, length = 100)
x <- model.matrix(COVIDseverity ~.,choc)[,-1]
y <- choc$severity
#lasso.mod <- glmnet(x[train,], y[train], alpha = 1, lambda = grid)
#plot(lass.mod)

#forward selection

# lm_model <- lm(as.numeric(COVIDseverity)~age_at_encounter ,data =choc )
# summary(lm_model)
# forward.model <- step(lm(COVIDseverity~1, data = na.omit(choc)), scope = list(upper=full.model), direction = "forward")
#+INOTROPES+REMDESIVIR+CCP+DEXAMETHASONE+ENOXAPARIN+HEPARIN+IVIG+METHYLPREDNISOLONE+TOCILIZUMAB+ASPIRIN+
# as.factor(comorb_bronchiectasis_J47)+
                  # as.factor(comorb_asthma_J45)+IMPORTANTas.factor(comorb_resp_failure_J96)+
                  #  as.factor(comorb_other_nutritional_deficiencies_E50_E64)+
                  #  as.factor(comorb_typeII_diabetes_E11)+as.factor(comorb_liver_disease_K70_K77)+
                  #  as.factor(comorb_essential_hypertension_I10)+
                  #  as.factor(comorb_chronic_kidney_disease_N18)+as.factor(comorb_heart_failure_I50)+
                  #  as.factor(comorb_lung_transplant_Z942)+
                  #  as.factor(comorb_ischemic_heart_disease_I20_I25)+
                  #  as.factor(comorb_nicotine_dependence_F17)+as.factor(comorb_hypertensive_heart_disease_I11)+
                  #  as.factor(comorb_other_GI_notLiver_K_excludesK70K77)+
                  #  as.factor(comorb_obesity_overweight_E66)+as.factor(comorb_typeI_diabetes_E10)+
                  #  as.factor(comorb_malnutrition)+as.factor(comorb_pneumothorax_J93)+
                  #  as.factor(comorb_nasal_polyps_J33)+as.factor(comorb_copd_J40_J44)


# +bmi_ratio+care_time+REMDESIVIR+CCP+
#                    +ENOXAPARIN+HEPARIN+as.factor(comorb_bronchiectasis_J47)+
#                    as.factor(comorb_asthma_J45)+as.factor(comorb_resp_failure_J96)+
#                    as.factor(comorb_other_nutritional_deficiencies_E50_E64)+
#                    as.factor(comorb_typeII_diabetes_E11)+as.factor(comorb_liver_disease_K70_K77)+
#                    as.factor(comorb_essential_hypertension_I10)+
#                    as.factor(comorb_chronic_kidney_disease_N18)+as.factor(comorb_heart_failure_I50)+
#                    as.factor(comorb_lung_transplant_Z942)+as.factor(comorb_ischemic_heart_disease_I20_I25)+
#                    as.factor(comorb_nicotine_dependence_F17)+as.factor(comorb_other_GI_notLiver_K_excludesK70K77)+ as.factor(comorb_obesity_overweight_E66)+as.factor(comorb_typeI_diabetes_E10)+
#                    as.factor(comorb_malnutrition)+as.factor(comorb_pneumothorax_J93)+
#                    as.factor(comorb_nasal_polyps_J33)+as.factor(comorb_copd_J40_J44)+INOTROPES+DEXAMETHASONE+IVIG+METHYLPREDNISOLONE+TOCILIZUMAB+ASPIRIN
```

```{r}
head(choc)
```


```{r}
choc_by_visit <- 
  mutate(comorb_groups, age_grp = case_when(age_at_encounter <7 ~'[0,6]', 
                                        age_at_encounter >6 & age_at_encounter <18~'[7,17]',
                                        age_at_encounter>17~'[18,25]')) %>% 
  mutate(age_grp = as.factor(age_grp)) %>% 
  mutate(comorb_type = case_when(has_comorb==1~a_func(comorb_groups, encounterid)
                                   ))
```


```{r}
clm2(location = COVIDseverity ~ care_time + age_at_encounter + 
    as.factor(comorb_bronchiectasis_J47) + as.factor(comorb_resp_failure_J96) + 
    as.factor(comorb_pneumothorax_J93) + as.factor(comorb_chronic_kidney_disease_N18) + 
    INOTROPES + DEXAMETHASONE + ENOXAPARIN + HEPARIN + METHYLPREDNISOLONE + 
    ASPIRIN, data = choc_by_visit, Hess = TRUE)


clm2(location = COVIDseverity ~ care_time + age_at_encounter + 
    as.factor(comorb_bronchiectasis_J47) + as.factor(comorb_resp_failure_J96) + 
    as.factor(comorb_pneumothorax_J93) + as.factor(comorb_chronic_kidney_disease_N18) + 
    INOTROPES + DEXAMETHASONE + ENOXAPARIN + HEPARIN + METHYLPREDNISOLONE + 
    ASPIRIN + as.factor(comorb_other_GI_notLiver_K_excludesK70K77) + 
    as.factor(comorb_hypertensive_heart_disease_I11) + as.factor(comorb_nicotine_dependence_F17), 
    data = choc_by_visit, Hess = TRUE)
#AIC = 4849.141

#AIC lowered by 1-3 if heart failure and lung transplant were added to the model (not worth the cost)


clmm2(location = COVIDseverity ~ care_time + age_at_encounter + 
    as.factor(comorb_bronchiectasis_J47) + as.factor(comorb_resp_failure_J96) + 
    as.factor(comorb_pneumothorax_J93) + as.factor(comorb_chronic_kidney_disease_N18) + 
    INOTROPES + DEXAMETHASONE + ENOXAPARIN + HEPARIN + METHYLPREDNISOLONE + 
    ASPIRIN + as.factor(comorb_other_GI_notLiver_K_excludesK70K77) + 
    as.factor(comorb_hypertensive_heart_disease_I11) + as.factor(comorb_nicotine_dependence_F17), 
    random = as.factor(personid), data = choc_by_visit, Hess = TRUE)
#AIC = 4332.623



```

```{r}
choc_by_visit <- choc_by_visit %>% 
  mutate(bin_COVIDseverity = case_when( COVIDseverity == 1|COVIDseverity == 2~1,
                                        COVIDseverity == 0~0))
```

**FOR NEO**  

```{r}
choc_by_visit <- mutate(choc_by_visit,
         resp = case_when(
           comorb_copd_J40_J44 == 1|
           comorb_nasal_polyps_J33 == 1|
           comorb_pneumothorax_J93==1|
           comorb_resp_failure_J96 == 1|
           comorb_asthma_J45 == 1 |
           comorb_bronchiectasis_J47 == 1~1,
           comorb_copd_J40_J44 == 0&
           comorb_nasal_polyps_J33 == 0&
           comorb_pneumothorax_J93==0&
           comorb_resp_failure_J96 == 0&
           comorb_asthma_J45 == 0&
           comorb_bronchiectasis_J47 == 0~0
            
         ), hemoptysis = comorb_hemoptysisR042, 
         nutrition = case_when(
           comorb_typeI_diabetes_E10 == 1|
           comorb_obesity_overweight_E66 ==1|
           comorb_typeII_diabetes_E11==1|
           comorb_other_nutritional_deficiencies_E50_E64 == 1|
           comorb_malnutrition == 1~1,
           comorb_typeI_diabetes_E10 == 0&
           comorb_obesity_overweight_E66 ==0&
           comorb_typeII_diabetes_E11==0&
           comorb_other_nutritional_deficiencies_E50_E64 == 0&
           comorb_malnutrition == 0~0
         ),
         gi = case_when(
           comorb_other_GI_notLiver_K_excludesK70K77 == 1|
           comorb_liver_disease_K70_K77 == 1~1,
           comorb_other_GI_notLiver_K_excludesK70K77 == 0&
           comorb_liver_disease_K70_K77 == 0~0
         ),
         cardio = case_when(
           comorb_hypertensive_heart_disease_I11 == 1|
           comorb_essential_hypertension_I10 == 1|
           comorb_heart_failure_I50==1|
           comorb_ischemic_heart_disease_I20_I25==1~1,
           comorb_hypertensive_heart_disease_I11 == 0&
           comorb_essential_hypertension_I10 == 0&
           comorb_heart_failure_I50==0&
           comorb_ischemic_heart_disease_I20_I25==0~0
         ),
         nicotine = case_when(
           comorb_nicotine_dependence_F17 == 1~1,
           comorb_nicotine_dependence_F17== 0~0
           
         ), 
         kidney = case_when(
           comorb_chronic_kidney_disease_N18 == 1~1,
           comorb_chronic_kidney_disease_N18 == 0~0
         ),
         lung_trans = case_when(
           comorb_lung_transplant_Z942 == 1~1, 
           comorb_lung_transplant_Z942 == 0~0
         )
         ) 

choc_by_visit <-  choc_by_visit %>% 
   mutate(has_comorb = case_when(comorb_bronchiectasis_J47==0&
             comorb_copd_J40_J44==0&
             comorb_asthma_J45==0&
             comorb_nasal_polyps_J33==0&
             comorb_hemoptysisR042==0&
             comorb_pneumothorax_J93==0&
             comorb_resp_failure_J96==0&
             comorb_malnutrition==0&
             comorb_other_nutritional_deficiencies_E50_E64==0&
             comorb_typeI_diabetes_E10==0&
             comorb_typeII_diabetes_E11==0&
             comorb_obesity_overweight_E66==0&
             comorb_liver_disease_K70_K77==0&
             comorb_other_GI_notLiver_K_excludesK70K77==0&
             comorb_essential_hypertension_I10==0&
             comorb_hypertensive_heart_disease_I11==0&
             comorb_chronic_kidney_disease_N18==0&
             comorb_nicotine_dependence_F17==0&
             comorb_heart_failure_I50==0&
             comorb_ischemic_heart_disease_I20_I25==0&
             comorb_lung_transplant_Z942==0~0,
             comorb_bronchiectasis_J47==1|
             comorb_copd_J40_J44==1|
             comorb_asthma_J45==1|
             comorb_nasal_polyps_J33==1|
             comorb_hemoptysisR042==1|
             comorb_pneumothorax_J93==1|
             comorb_resp_failure_J96==1|
             comorb_malnutrition==1|
             comorb_other_nutritional_deficiencies_E50_E64==1|
             comorb_typeI_diabetes_E10==1|
             comorb_typeII_diabetes_E11==1|
             comorb_obesity_overweight_E66==1|
             comorb_liver_disease_K70_K77==1|
             comorb_other_GI_notLiver_K_excludesK70K77==1|
             comorb_essential_hypertension_I10==1|
             comorb_hypertensive_heart_disease_I11==1|
             comorb_chronic_kidney_disease_N18==1|
             comorb_nicotine_dependence_F17==1|
             comorb_heart_failure_I50==1|
             comorb_ischemic_heart_disease_I20_I25==1|
             comorb_lung_transplant_Z942==1
              ~1
            ))

choc_by_visit_noNA <- choc_by_visit[!is.na(choc_by_visit$care_time), ]

choc_by_visit_noNA <- choc_by_visit_noNA %>% 
  mutate(has_trt = case_when(INOTROPES == 1 |
                            REMDESIVIR==1|
                            DEXAMETHASONE==1|
                            HEPARIN==1|
                            METHYLPREDNISOLONE==1|
                            TOCILIZUMAB==1|
                            LOPINAVIR_OR_RITONAVIR==1|
                            ASPIRIN==1|
                            RITUXIMAB==1|
                            IVIG==1|
                            ENOXAPARIN==1|
                            CCP==1~1,TRUE~0))

 glm.group <- glm(as.factor(bin_COVIDseverity) ~ care_time + age_at_encounter + as.factor(resp)+ as.factor(nutrition)+ as.factor(gi) + as.factor(cardio)+as.factor(nicotine)+as.factor(kidney)+ as.factor(lung_trans)+as.factor(hemoptysis) +as.factor(anticoagulant) + as.factor(anti_inflamitory)+
                    as.factor(anti_viral)+as.factor(immuno), data = choc_by_visit,
                  family =binomial(link  = "logit"))
 summary(glm.group)
 
 
 glm.reduced <- glm(as.factor(bin_COVIDseverity) ~ as.factor(has_comorb)+as.factor(has_trt)+care_time + age_at_encounter, data = choc_by_visit_noNA, family= binomial(link = "logit") )
summary(glm.reduced)

```

