---
title: "Model Dev"
author: "Neo Raquinio"
date: '2022-07-06'
output: html_document
---

```{r}
library(tidyverse)
library(knitr)
library(ggpubr)
library(leaps)
library(glmnet)
library(AICcmodavg)
library(caret)
rownames(d) <- seq(1,nrow(d))
```


# Subsettng the data based on treatment 

# Does not include oxygen support as they directly define covid severity in the 
# data set (ECMO, BiPAP, invasive Ventilisation, etc.)
```{r}

med_severity <- d %>%
  select(personid, COVIDseverity, INOTROPES, REMDESIVIR, CCP, DEXAMETHASONE,
         ENOXAPARIN, HEPARIN, IVIG, METHYLPREDNISOLONE, RITUXIMAB, TOCILIZUMAB,
         ASPIRIN, LOPINAVIR_OR_RITONAVIR)

# regsubsets(COVIDseverity ~., med_severity, really.big = TRUE)



med_severity <- med_severity %>% 
  mutate(
    anticoagulant = case_when(
      ENOXAPARIN == 1|
      HEPARIN == 1~1,
      ENOXAPARIN == 0&
      HEPARIN == 0~0),
    
    anti_inflamitory = case_when(
      DEXAMETHASONE == 1|
      METHYLPREDNISOLONE ==1|
      TOCILIZUMAB == 1|
      ASPIRIN == 1~1,
      DEXAMETHASONE == 0&
      METHYLPREDNISOLONE == 0&
      TOCILIZUMAB == 0&
      ASPIRIN == 0~0),
    
    anti_viral = case_when(
      REMDESIVIR == 1|
      LOPINAVIR_OR_RITONAVIR == 1~1,
      REMDESIVIR == 0&
      LOPINAVIR_OR_RITONAVIR == 0~0),
    
    immuno = case_when(
      CCP == 1|
      IVIG == 1|
      RITUXIMAB == 1~1,
      CCP == 0&
      IVIG == 0&
      RITUXIMAB == 0~0)
     )

medgroup_severity <- med_severity %>% 
  select(COVIDseverity, anticoagulant, anti_inflamitory, anti_viral, immuno)

regfit.medgroup <- regsubsets(COVIDseverity ~., medgroup_severity)
summary(regfit.medgroup)
```



```{r}
med_group_severity <- med_severity %>% 
  select(COVIDseverity, anticoagulant, anti_inflamitory, anti_viral, immuno) %>% 
  mutate(COVIDseverity = as.factor(as.character(COVIDseverity)))



x <- model.matrix(COVIDseverity ~., med_group_severity)[,-1]
y <- med_group_severity$COVIDseverity

grid <- 10^seq(10,-2,length = 100)

ridge_med_mod <- glmnet(x, y, alpha = 0, lambda = grid, family = "multinomial")

dim(coef(ridge_med_mod))

ridge_med_mod$lambda

predict(ridge_med_mod, s = 30, type = "coefficients")

``` 



```{r}

choc_comorb_med <- d %>% 
  select(
    COVIDseverity,
    contains("comorb"),
    admit_tempC,
    heartrate,
    respiratoryrate,
    spo2,
    bmi_percentile,
    bmi_ratio,
    systolicBP,
    diastolicBP,
    bilirubin_total_mg_per_dl,
    crp_mg_dl,
    leukocytes_1000_per_uL,
    lymphocytes_1000_per_uL,
    hemoglobin_g_per_dL,
    platelets_1000_per_uL,
    ALP_U_per_L,
    ALT_U_per_L,
    AST_U_per_L,
    LDH_U_per_L,
    ferritin_ng_per_mL
  )


# choc_comorb_med_sub <- choc_comorb_med %>% 
#   mutate( COVIDseverity =
#     case_when( 
#     COVIDseverity > "0" ~ "1",
#     COVIDseverity == "0" ~ "0"
#     )
#   )

choc_sub_fac <- choc_comorb_med %>% 
  mutate( 
    COVIDseverity = case_when(
      COVIDseverity == 0 ~ 0,
      COVIDseverity == 1 ~ 1,
      COVIDseverity == 2 ~ 1
    ))


  

choc_sub_fac <- choc_sub_fac %>% 
  mutate(
    COVIDseverity = as.factor(as.character(COVIDseverity))
  )

choc.1 <- choc_sub_fac %>% 
  mutate_if(is.factor, as.character)

choc.2 <- choc.1 %>% 
  mutate_if(is.character, as.integer)

```



```{r}

cor(choc.2)

choc.2_sub <- regsubsets(COVIDseverity ~., data = choc.2, nvmax = 4)
summary(choc.2_sub)


########

resp.glm <- glm(COVIDseverity ~ comorb_bronchiectasis_J47 + comorb_copd_J40_J44 + 
                  comorb_asthma_J45 + comorb_nasal_polyps_J33 + 
                  comorb_hemoptysisR042 + comorb_pneumothorax_J93 +
                  comorb_resp_failure_J96, data = choc.2, family = binomial)

summary(resp.glm)
coef(resp.glm)

choc.2_resp_sub <- regsubsets(COVIDseverity ~comorb_bronchiectasis_J47 + comorb_copd_J40_J44 + 
                  comorb_asthma_J45 + comorb_nasal_polyps_J33 + 
                  comorb_hemoptysisR042 + comorb_pneumothorax_J93 +
                  comorb_resp_failure_J96, data = choc.2, nvmax = 4)
summary(choc.2_resp_sub)
######

gi.glm <- glm(COVIDseverity ~ comorb_liver_disease_K70_K77 + 
                comorb_other_GI_notLiver_K_excludesK70K77, 
              data = choc.2, family = binomial)

summary(gi.glm)
coef(gi.glm)

choc.2_gi_sub <- regsubsets(COVIDseverity ~ comorb_liver_disease_K70_K77 + 
                comorb_other_GI_notLiver_K_excludesK70K77, data = choc.2, nvmax = 2)

summary(choc.2_gi_sub)

##########

vitals.glm <- glm(COVIDseverity ~ admit_tempC + heartrate + respiratoryrate + bmi_ratio + spo2 +
      bmi_percentile + systolicBP + diastolicBP, data = choc.2, family = binomial)

summary(vitals.glm)
coef(vitals.glm)


choc.2_vitals_sub <-  regsubsets(COVIDseverity ~ admit_tempC + heartrate +
                                   respiratoryrate + bmi_ratio + spo2 +
      bmi_percentile + systolicBP + diastolicBP, data = choc.2, nvmax = 4)

summary(choc.2_vitals_sub)
########

lab1.glm <- glm(COVIDseverity ~ bilirubin_total_mg_per_dl + crp_mg_dl + leukocytes_1000_per_uL +
      lymphocytes_1000_per_uL + ALP_U_per_L + ALT_U_per_L + AST_U_per_L + LDH_U_per_L +    ferritin_ng_per_mL, 
    data = choc.2, family = binomial)

labt3.glm <- glm(COVIDseverity ~ LDH_U_per_L + AST_U_per_L + ALP_U_per_L, data = choc.2, 
    family = binomial)

labt6.glm <- glm(COVIDseverity ~ LDH_U_per_L + AST_U_per_L + ALP_U_per_L + ferritin_ng_per_mL + 
      leukocytes_1000_per_uL + lymphocytes_1000_per_uL, data = choc.2, 
    family = binomial)

summary(lab1.glm)
coef(lab1.glm)

summary(labt3.glm)
coef(labt3.glm)

summary(labt6.glm)

choc.2_lab_sub <- regsubsets(COVIDseverity ~ bilirubin_total_mg_per_dl + crp_mg_dl +
             leukocytes_1000_per_uL + lymphocytes_1000_per_uL + 
             ALP_U_per_L + ALT_U_per_L + AST_U_per_L + LDH_U_per_L + 
             ferritin_ng_per_mL, data = choc.2, nvmax = 6)
print(summary(choc.2_lab_sub))

####### AIC of models

models <-  list(resp.glm, gi.glm, vitals.glm, lab1.glm, labt3.glm, mix.glm)
mod.names <-  c("resp.glm", "gi.glm", "vitals.glm", "lab1.glm", "labt3.glm" ,"mix.glm")

aictab(cand.set = models, modnames = mod.names)

# K: The number of parameters in the model.
# AICc: The AIC value of the model. The lowercase ‘c’ indicates that the AIC has been calculated from the AIC corrected for small sample sizes.
# Delta_AICc: The difference between the AIC of the best model compared to the current model being compared.
# AICcWt: The proportion of the total predictive power that can be found in the model.
# Cum.Wt: The cumulative sum of the AIC weights.
# LL: The log-likelihood of the model. This tells us how likely the model is, given the data we used.
```


```{r}

mix.glm <- glm(COVIDseverity ~ comorb_resp_failure_J96 + comorb_bronchiectasis_J47 + 
      comorb_other_GI_notLiver_K_excludesK70K77 + comorb_liver_disease_K70_K77 +
      spo2 + bmi_ratio + respiratoryrate + LDH_U_per_L + AST_U_per_L + ALP_U_per_L,
    data =choc.2, family = binomial)

summary(mix.glm)
coef(mix.glm)

```
```{r}
choc.2 <- data.frame(choc.2)

rownames(choc.2) <- seq(1, nrow(choc.2))
view(choc.2)


a = seq(1, 9337, 1)
b = sample(a, 7470, replace = F)

choc_train = choc.2[b,]
choc_test = choc.2[-b,]

########################

resp.glm_test <- glm(COVIDseverity ~ comorb_bronchiectasis_J47 + comorb_copd_J40_J44 + 
                  comorb_asthma_J45 + comorb_nasal_polyps_J33 + 
                  comorb_hemoptysisR042 + comorb_pneumothorax_J93 +
                  comorb_resp_failure_J96, data = choc_train, family = binomial)

resp.glm_pred <- predict(resp.glm_test, newdata = choc_test)

lSSE.resp = log(sum((resp.glm_pred - choc_test$COVIDseverity)^2))

########################

gi.glm_train <- glm(COVIDseverity ~ comorb_liver_disease_K70_K77 + 
                comorb_other_GI_notLiver_K_excludesK70K77, 
              data = choc_train, family = binomial)

gi.glm_pred <- predict(gi.glm_train, newdata =  choc_test)

lSSE.gi <- log(sum((gi.glm_pred - choc_test$COVIDseverity)^2))

########################

vitals.glm_train <- glm(COVIDseverity ~ admit_tempC + heartrate + respiratoryrate + 
                          bmi_ratio + spo2 + bmi_percentile + systolicBP +
                          diastolicBP, data = choc_train, family = binomial)

vitals.glm_pred <- predict(vitals.glm_train, newdata = choc_test)

lSSE.vitals <- log(sum(na.omit((vitals.glm_pred - choc_test$COVIDseverity)^2)))

########################

lab1.glm_train <- glm(COVIDseverity ~ bilirubin_total_mg_per_dl + crp_mg_dl + 
                        leukocytes_1000_per_uL +lymphocytes_1000_per_uL +
                        ALP_U_per_L + ALT_U_per_L + AST_U_per_L + LDH_U_per_L +
                        ferritin_ng_per_mL, data = choc_train, family = binomial)

lab1.glm_pred <- predict(lab1.glm_train, newdata = choc_test)

lSSE.lab1 <- log(sum(na.omit((lab1.glm_pred - choc_test$COVIDseverity)^2)))

########################

########################
```

