---
title: "Liz Comorb Stuff"
author: "Team 6"
date: '2022-07-01'
output: html_document
---

```{r setup, warning = FALSE, include = FALSE}

setwd("C:/Users/lizvi/Cal State Fullerton/Jaynes, Jessica - CSUF CHOC Summer 2022 Research/Group2")

load("cfCOVIDgroup6.RDATA")


library(tidyverse)
library(data.table)
library(gganimate)
library(gifski)
library(reshape2)
library(viridis)
library(glmnet)


all_comorb <- dplyr::select(d, contains("comorb"))

glimpse(all_comorb)

attach(d)
```


```{r warning = FALSE}

all_comorb <- all_comorb %>% mutate_if(is.factor, as.numeric) %>% 
  -1

all_comorb <- all_comorb %>% 
  mutate(total_comorb_by_patient = c(rowSums(all_comorb)), 
         COVIDseverity = d[,73], age_at_encounter = d[,11], service_date = as.Date(d[,9]))

all_comorb %>% 
  summarize(mean_total = mean(total_comorb_by_patient), med_total = median(total_comorb_by_patient), max_total = max(total_comorb_by_patient),
            var_total = var(total_comorb_by_patient))
detach(d)

attach(all_comorb)

colSums(all_comorb[,1:21])

grouped_comorb <- data.frame( 
  select(all_comorb, contains("J")) %>% 
    sum(), 
  select(all_comorb, contains("K", ignore.case = FALSE)) %>% 
    sum(), 
  select(all_comorb, contains("E", ignore.case = FALSE), contains("nutrition")) %>% 
    sum(), 
  select(all_comorb, contains("I", ignore.case = FALSE) & 
         !contains("E", ignore.case = FALSE) & 
         !contains("K", ignore.case =  FALSE) &
         !contains("COVIDseverity")) %>% 
    sum(),
  sum(comorb_chronic_kidney_disease_N18), sum(comorb_hemoptysisR042),                  sum(comorb_lung_transplant_Z942), 
  sum(comorb_nicotine_dependence_F17)) %>% 
    colSums() %>% 
  melt(value.name = 'Patients') %>% 
  mutate(comorbidity = c("Respiratory", "GI", "Nutrition", 
                  "Cardiovascular", "Chronic Kidney Disease", "Hemoptysis", "Lung Transplant", "Nicotine Dependence"))



grouped_comorb %>% 
  ggplot(aes(x = comorbidity, y = Patients)) +
  geom_bar(stat = 'identity')

all_comorb %>% 
  ggplot(aes(x = total_comorb_by_patient)) +
  geom_bar(data = subset(all_comorb, total_comorb_by_patient > 0), fill = "lightsteelblue") +
  scale_x_continuous(breaks = c(1:10)) +
  xlab("Total Number of Comorbidities") +
  ylab("Patients")

all_comorb %>% 
  ggplot(aes(x = total_comorb_by_patient)) +
  geom_bar(fill = "lightsteelblue") +
  scale_x_continuous(breaks = c(0:10)) +
  xlab("Total Number of Comorbidities per Patient") +
  ylab("Patients") +
  facet_wrap(COVIDseverity)


```


```{r}
all_comorb %>% 
  ggplot(aes(x = total_comorb_by_patient, fill = COVIDseverity)) +
  geom_bar() +
  scale_x_continuous(breaks = c(0:10)) +
  xlab("Total Number of Comorbidities per Patient") +
  ylab("Patients") 
 


```


```{r}
all_comorb %>% 
  ggplot(aes(x = COVIDseverity)) +
  geom_bar(fill = "lightsteelblue") +
  xlab("COVID_19 Severity") +
  ylab("Patients") +
  facet_wrap(total_comorb_by_patient)
```


```{r}
include <- ggplot(all_comorb, aes(total_comorb_by_patient, 
                                  fill = as.factor(age_at_encounter))) +
  geom_bar(show.legend = FALSE) +
  scale_x_continuous(breaks = c(0:10)) +
  labs(title = 'Age: {as.integer(frame_time)}', x = 'Total Comorbidities per Patient',
       y = 'Number of Patients') +
  transition_time(age_at_encounter) +
  ease_aes('linear') +
  theme_bw() +
  theme(text = element_text(size = 15)) +
  scale_fill_manual(values = c(viridis_pal(option = "C")(26)))
animate(include, fps = 4)


```


```{r}
ggplot(all_comorb, aes(total_comorb_by_patient, fill = COVIDseverity)) +
  geom_bar(position = "fill") +
  scale_x_continuous(breaks = c(0:10)) +
  labs(x = 'Comorbidities per Patient', y = 'Proportion',
       fill = 'COVID-19 Severity') +
  scale_fill_manual(values = c('#EDD9A3', '#F2637F', '#872CA2'), labels = 
                      c("Mild", "Moderate", "Severe")) +
  theme_bw() +
  theme(text = element_text(size = 15))
```


```{r}
age_sever <- ggplot(all_comorb, aes(age_at_encounter, fill = COVIDseverity)) +
  geom_bar(position = "fill", show.legend = FALSE) +
  scale_x_continuous(breaks = c(0:25)) +
  labs(x = 'Age', y = 'Proportion',
       fill = 'COVID-19 Severity') +
  scale_fill_manual(values = c('#EDD9A3', '#F2637F', '#872CA2'), labels = 
                      c("Mild", "Moderate", "Severe")) +
  theme_bw() +
  theme(text = element_text(size = 15))
```



```{r}
weirdograph <- 
  all_comorb %>% 
  filter(COVIDseverity > 0) %>% 
  ggplot(aes(total_comorb_by_patient,
         fill = COVIDseverity)) +
  geom_bar(position = "fill", aes(color = COVIDseverity)) +
  scale_x_continuous(breaks = c(0:10)) +
  labs(title = 'Age: {as.integer(frame_time)}', x = 'Total Comorbidities per Patient',
       y = 'Number of Patients') +
  transition_time(age_at_encounter) +
  theme_bw() +
  theme(text = element_text(size = 15))

animate(weirdograph, nframes = 25, fps = 1)

  
```

```{r}
 weirdo2 <-  all_comorb %>% 
  filter(COVIDseverity > 0) %>% 
  ggplot(aes(total_comorb_by_patient,
         fill = COVIDseverity)) +
  geom_bar() +
  scale_x_continuous(breaks = c(0:10)) +
  labs(title = 'Age: {as.integer(frame_time)}', x = 'Total Comorbidities per Patient',
       y = 'Number of Patients') +
  transition_time(age_at_encounter) +
  theme_bw() +
  theme(text = element_text(size = 15))
weirdo2 + scale_color_brewer()
  animate(weirdo2, nframes = 25, fps = 1)
```


```{r}
all_comorb %>% 
  ggplot(aes(age_at_encounter)) +
  geom_density(aes(fill = factor(total_comorb_by_patient))) +
  facet_wrap(COVIDseverity)
```


```{r}
all_comorb <- all_comorb %>% 
  mutate(resp_total = rowSums(select(all_comorb, contains("J"))), gi_total =
           rowSums(select(all_comorb, contains("K", ignore.case = FALSE))), other_total = rowSums(select(all_comorb, contains("comorb") &                                                     !contains("J") & !contains("K", ignore.case = FALSE)                                 & !contains("patient"))))

col_stackt_df <- 
  rbind(
  all_comorb %>% 
  filter(resp_total > 0 & gi_total == 0 & other_total == 0) %>%
  select(COVIDseverity, age_at_encounter) %>% 
  mutate(class = 'Respiratory'), 
  
  all_comorb %>% 
  filter(resp_total == 0 & gi_total > 0 & other_total == 0) %>% 
  select(COVIDseverity, age_at_encounter) %>% 
  mutate(class = 'GI'),
  
  all_comorb %>% 
  filter(resp_total == 0 & gi_total == 0 & other_total > 0) %>% 
  select(COVIDseverity, age_at_encounter) %>% 
  mutate(class = 'Other'), 
  
  all_comorb %>% 
  filter(resp_total == 0 & gi_total == 0 & other_total == 0) %>%
  select(COVIDseverity, age_at_encounter) %>% 
  mutate(class = 'None'))
```


```{r}
col_stackt_df %>% 
  ggplot(aes(x = COVIDseverity, fill = class)) +
  geom_bar(position = 'dodge')
```


```{r}
percent_sever <- col_stackt_df %>%
    count(COVIDseverity, class) %>%
    group_by(COVIDseverity) %>%
    mutate(percent = (n / sum(n)) * 100) %>%
    ungroup()

percent_sever_no <- col_stackt_df %>%
    filter(class != "None") %>% 
    count(COVIDseverity, class) %>%
    group_by(COVIDseverity) %>%
    mutate(percent = (n / sum(n)) * 100) %>%
    ungroup()

```

```{r}
percent_sever %>% 
  ggplot(aes(x = COVIDseverity, y = percent, fill = class)) +
  geom_bar(stat = 'identity', position = 'dodge')



percent_sever_no %>% 
  ggplot(aes(x = COVIDseverity, y = percent, fill = class)) +
  geom_bar(stat = 'identity', position = 'dodge')
```


```{r}
col_stackt_df %>% 
  ggplot(aes(x = age_at_encounter, after_stat(density), color = class)) +
  geom_freqpoly(binwidth = 5)
```


Preparing data frame for LASSO, I am classifying all cases that require oxygen
intervention, identified by "1" and "2" under the COVIDseverity variable in the
original data set, as severe, which will now be identified as "1". All mild
cases will remain as "0".
```{r}
lasso_comorb <- all_comorb %>% 
  mutate(COVIDseverity = case_when(COVIDseverity > "0" ~ "1",
                                   COVIDseverity == "0" ~ "0"))

lasso_comorb <- lasso_comorb[,c(1:21, 23)] %>% 
  mutate_if(is.numeric, as.factor) %>% 
  cbind(all_comorb[,c(22, 24, 26:28)])


```


LASSO ?!!!?!!!
```{r}
set.seed(36323)
x <-  model.matrix(COVIDseverity ~., lasso_comorb)[, -1]
y <-  lasso_comorb$COVIDseverity
dim(x)
grid <- 10^seq(10, -2, length = 100)

train <-  sample(nrow(x), size = floor(.75 * nrow(x)))
test <-  (-train)
y_test <-  y[test]

lasso_mod <-  glmnet(x[train, ], y[train], alpha = 1,
                     lambda = grid, family = "binomial")

cv_out <- cv.glmnet(x[train, ], y[train], alpha = 1, family = "binomial")

best_lam <-  cv_out$lambda.min

lasso_pred <-  predict(lasso_mod, s = best_lam, newx = x[test, ])

out <-  glmnet(x, y, alpha = 1, lambda = grid, family = "binomial")

lasso_coef = predict(out, type = "coefficients",
                         s = best_lam)[1:26, ]

lasso_coef[lasso_coef != 0]
```


How 'bout linear discriminant analysis?????!!!!!!!!!?!?!?!?!?
```{r}
library(MASS)

lda_comorb <- all_comorb[, c(1, 6:8, 14, 16:19, 21:23)]

train_lda <-  sample(nrow(lda_comorb), size = floor(.75 * nrow(lda_comorb)))

train_lda.df <-  as.data.frame(lda_comorb[train_lda,])

test_lda.df <-  as.data.frame(lda_comorb[-train_lda,])

```

lord help me

```{r}
f <- paste(names(train_lda.df)[12], "~", paste(names(train_lda.df)[-12],
                                               collapse = " + "))

lda_fit <- lda(as.formula(paste(f)), data = train_lda.df)
lda_fit

plot(lda_fit)

lda_class <- predict(lda_fit, test_lda.df)$class
```


```{r}
table(lda_class, test_lda.df[,"COVIDseverity"])
```


```{r}
test_cs <- test_lda.df[,"COVIDseverity"]
lda_class <- as.ordered(lda_class)
mean(lda_class == test_cs)
```

```{r}
lasso_comorb <- lasso_comorb %>% mutate_if(is.numeric, as.factor)

lr_comorb <- glm(COVIDseverity ~ comorb_bronchiectasis_J47 + comorb_pneumothorax_J93 + comorb_resp_failure_J96 + comorb_malnutrition + comorb_other_GI_notLiver_K_excludesK70K77 + comorb_hypertensive_heart_disease_I11 + comorb_chronic_kidney_disease_N18 + comorb_nicotine_dependence_F17 + comorb_heart_failure_I50 + comorb_lung_transplant_Z942 + total_comorb_by_patient, family = "binomial", data = lasso_comorb)

summary(lr_comorb)
```


```{r}
library(heplots)
boxM(lda_comorb[,1:11], lda_comorb[,12])
```

Sooooooooooo we don't meet the assumptions necessary for LDA :/




